### ISSUE TITLE
Examples: SceneKit examples crashes /bc of nil

### ISSUE THREAD

**Issue by MartinMajewski** [mapbox/mapbox-maps-ios#596] opened 2021-08-16 07:38 UTC
## Environment

- Xcode version: 12.5.1
- iOS version: Simulator - 14.5

## Observed behavior and steps to reproduce

- Starting the Examples project and navigating to "SceneKit rendering on map" example.
- Nil error on line 81 of SceneKitExample.swift
- crash

![Screenshot 2021-08-16 at 09 37 02](https://user-images.githubusercontent.com/2221289/129527889-05bf3e40-2505-4435-89a4-b78e85488205.png)

What more information shall I provide?

**Comment by macdrevx** [comment] 2021-08-17 15:32
Hi @MartinMajewski, I just tried running this example using the latest commit on the main branch, and I was unable to reproduce this crash. To help us further investigate this issue could you please…

* Try resetting your simulator, cleaning your project, and running again?
* Tell us which commit you're working off of and whether you have any local changes?

**Comment by MartinMajewski** [comment] 2021-08-18 09:52
Hi @macdrevx 

so I've cloned the repository anew (master branch, no changes made!) and opened Apps.xcworkspace in XCode.

I've selected "Examples > iPhone 11 Pro Max" as the target and run the project.
Showing a simple map worked fine. However, I got the same nil exception.
In the logs, I saw that the app had some errors regarding the token, which is correctly set in the .netrc file.

So I did a simulator reset and restarted the project. No, neither a simple map is shown, nor the SceneKit example is working.
However, it does not crash with nil (which could be prevented by implementing a proper guard statement in front of the optional) but shows simply nothing (black screen).

The log output is:

```
2021-08-18 11:15:06.486370+0200 Examples[11671:826962] Metal GPU Frame Capture Enabled
2021-08-18 11:15:06.487104+0200 Examples[11671:826962] Metal API Validation Enabled
2021-08-18 11:15:06.548578+0200 Examples[11671:826962] <maps> Using Metal render backend
2021-08-18 11:15:06.675566+0200 Examples[11671:827134] [connection] nw_proxy_resolver_create_parsed_array [C1 proxy pac] Evaluation error: kCFErrorDomainCFNetwork: 308
2021-08-18 11:15:06.708569+0200 Examples[11671:827134] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
2021-08-18 11:15:06.945710+0200 Examples[11671:827527] <maps> {}[Setup]: Failed to load style: HTTP status code 401
2021-08-18 11:15:07.021084+0200 Examples[11671:827519] [connection] nw_proxy_resolver_create_parsed_array [C2 proxy pac] Evaluation error: kCFErrorDomainCFNetwork: 308
2021-08-18 11:15:07.070751+0200 Examples[11671:827433] [connection] nw_proxy_resolver_create_parsed_array [C3 proxy pac] Evaluation error: kCFErrorDomainCFNetwork: 308
2021-08-18 11:15:55.466546+0200 Examples[11671:826962] <maps> Using Metal render backend
2021-08-18 11:15:55.514538+0200 Examples[11671:828714] [connection] nw_proxy_resolver_create_parsed_array [C4 proxy pac] Evaluation error: kCFErrorDomainCFNetwork: 308
2021-08-18 11:15:55.667630+0200 Examples[11671:827527] <maps> {}[Setup]: Failed to load style: HTTP status code 401
2021-08-18 11:16:25.445099+0200 Examples[11671:826962] <maps> Using Metal render backend
2021-08-18 11:16:25.552072+0200 Examples[11671:827527] <maps> {}[Setup]: Failed to load style: HTTP status code 401
```

401 means "unauthorized" which can only mean that the token is invalid, but it should not be!

Anyhow, I've created a new token, put it in .netrc, did a simulator reset, and restarted the project.

Same issue.

Then I looked up your script that is called during the last build phase and what hit my attention is that there is no mentioning of **.netrc** but .mapbox. However, in every single Readme.md you state .netrc as the place where the secret token has to go.

Doesn't matter, because I have the correct secret token already set in .mapbox and I can run my own application without a 401 issue.

Furthermore, the beforementioned script is only called if something significant has changed. This is bad if one just wants to rotate the token without changing anything else. It should be called every time!

![Screenshot 2021-08-18 at 11 27 33](https://user-images.githubusercontent.com/2221289/129875503-4915f729-4223-4b82-8e5c-f6c4fbb983d3.png)

**Comment by macdrevx** [comment] 2021-08-18 14:19
Hi @MartinMajewski, thanks for the detailed update.

Re: the tokens, there are actually 2 different tokens involved:

* A secret token in `~/.netrc` -- this one is used when installing dependencies
* A public token in `~/.mapbox` (or directly in the Examples App's Info.plist) -- this one is used at runtime to access Mapbox APIs

See https://docs.mapbox.com/ios/maps/guides/install/ for more details on both of these.

Re: the build script not being invoked if the .mapbox file changes — yes, I agree this seems like a bug in our build configuration. I'll create a ticket for us to address this.

I tried reproducing the issue again using the same simulator you mentioned, and I'm still unable to reproduce the error. As a next step, could you try replacing line 80 as shown in the screenshot above with the following:

```
        do {
            if let url = Bundle.main.url(forResource: "34M_17", withExtension: "dae") {
                modelNode = try SCNScene(url: url, options: nil).rootNode.clone()
            } else {
                print("Unable to get URL for 34M_17.dae")
            }
        } catch {
            print(error)
        }
```

When you do that, could you let me know what output you're seeing?

**Comment by MartinMajewski** [comment] 2021-08-18 14:43
I will do.

Currently, I'm trying to get the simple map view to work in the Examples map.
I have the public key placed in .mapbox but nothing.
While placing it in the info.plist file (Examples -> Examples folder -> Info.plist) there is a variable called "MBXAccessToken".
What is this? In the documentation you've mentioned the variable is refered to as "MGLMapboxAccessToken".

Is this just outdated documentation?

In my own app, I have placed the private token directly inside the 
```myResourceOptions = ResourceOptions(accessToken: PUBLIC-TOKEN)```
method. This works for me, but the example app does not. Still Error 401.

I'm having also a hard time getting MapBox working with SwiftUI and SceneKit. The examples provided for both topics are not easy to be merged. Somehow, I cannot add a CustomLayer, but I have currently no clue what's the matter here.

**Comment by macdrevx** [comment] 2021-08-18 14:50
> Is this just outdated documentation

Yes, the doc I linked to has not been updated for v10 yet. In v10 the Info.plist key for the public token is `MBXAccessToken`

**Comment by MartinMajewski** [comment] 2021-08-18 14:55
Okay, but unfortunately no success getting the map being displayed.
I deployed the app also on my physical device that is also an iPhone Pro 11 Max but I get a dark screen an this log output:

```
2021-08-18 16:53:40.771579+0200 Examples[14889:6080336] <maps> Using Metal render backend
2021-08-18 16:53:40.773809+0200 Examples[14889:6080336] Metal GPU Frame Capture Enabled
2021-08-18 16:53:40.774088+0200 Examples[14889:6080336] Metal API Validation Enabled
2021-08-18 16:53:41.140706+0200 Examples[14889:6080515] [connection] nw_endpoint_handler_set_adaptive_read_handler [C1.1.1 99.86.7.140:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
2021-08-18 16:53:41.140742+0200 Examples[14889:6080515] [connection] nw_endpoint_handler_set_adaptive_write_handler [C1.1.1 99.86.7.140:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
2021-08-18 16:53:41.340396+0200 Examples[14889:6080532] <maps> {}[Setup]: Failed to load style: HTTP status code 401
2021-08-18 16:53:41.399688+0200 Examples[14889:6080509] [connection] nw_endpoint_handler_set_adaptive_read_handler [C2.1.1 54.77.213.167:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
2021-08-18 16:53:41.399793+0200 Examples[14889:6080509] [connection] nw_endpoint_handler_set_adaptive_write_handler [C2.1.1 54.77.213.167:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
2021-08-18 16:53:41.401178+0200 Examples[14889:6080509] [connection] nw_endpoint_handler_set_adaptive_read_handler [C3.1.1 52.211.122.2:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
2021-08-18 16:53:41.401250+0200 Examples[14889:6080509] [connection] nw_endpoint_handler_set_adaptive_write_handler [C3.1.1 52.211.122.2:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
```

**Comment by macdrevx** [comment] 2021-08-18 16:10
Since you're able to build and run, your secret token/.netrc must be fine. The issue will be with your public token.

Could you try inserting the public token in code when the MapView is initialized so that we can rule out an issue with your public token?

The `nw_endpoint_handler_set_adaptive_*` logs are coming from Apple frameworks. We've opened tickets about them with Apple. Some of these should be resolved in iOS 15. As far as we can tell, they're just informational and not indicative of anything going wrong that would impact the SDK.

**Comment by MartinMajewski** [comment] 2021-08-18 16:51
Please give me a second.

One more question: where does the "water" layer come from? When I add a custom layer to my own application I get an error, that such a layer with this id does not exist. I can only use `.default` as layerPosition.

**Comment by MartinMajewski** [comment] 2021-08-18 17:19
Okay, so putting the same public key directly into the code worked!

I did it like this:

```
    override public func viewDidLoad() {
        super.viewDidLoad()

        let camera = CameraOptions(center: self.modelOrigin,
                                   zoom: 18,
                                   bearing: 180,
                                   pitch: 60)
        
        let resourceOptions = ResourceOptions(accessToken: "pk.eyJ1IjoibWFyd ...  ... Y5x6xM92JknEUogGH7EB0A")
        
        let options = MapInitOptions(resourceOptions: resourceOptions, cameraOptions: camera)

        mapView = MapView(frame: view.bounds, mapInitOptions: options)
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        view.addSubview(mapView)

        mapView.mapboxMap.onNext(.styleLoaded) { _ in
            self.addModelAndTerrain()
        }
    }
```

Now, at least for the SceneKit example, I get a white screen and a crash... but now I know why...

**...drumroll...**

![Screenshot 2021-08-18 at 18 55 00](https://user-images.githubusercontent.com/2221289/129941810-4322013a-4e28-47f4-9fd5-f6d42e43b68c.png)

```
Error Domain=NSCocoaErrorDomain Code=259 "The document "34M_17.dae" could not be opened." UserInfo={NSURL=file:///var/containers/Bundle/Application/DA425622-7FD0-4E8E-A21C-96878676A76A/Examples.app/34M_17.dae, NSLocalizedDescription=The document "34M_17.dae" could not be opened., NSLocalizedRecoverySuggestion=Collada is not supported by this version of SceneKit}
Examples/SceneKitExample.swift:93: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
2021-08-18 18:53:57.908109+0200 Examples[15088:6132006] Examples/SceneKitExample.swift:93: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```



### **Collada files cannot be opened!**

Quick search: https://stackoverflow.com/questions/38686278/loading-collada-file-from-webserver-in-scenekit

Okay, so one has to put the Collada file into a scene converting it this way.

![Screenshot 2021-08-18 at 19 05 49](https://user-images.githubusercontent.com/2221289/129941842-511fe6ac-f142-42fb-8846-fa55e281f230.png)

![Screenshot 2021-08-18 at 19 17 33](https://user-images.githubusercontent.com/2221289/129943191-885707e9-d1ef-4a1c-b6a4-a8729bdcc0b4.png)


The result is, however, a flipped deep space antenna.
But this is just a config issue.

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-08-18 at 19 09 39](https://user-images.githubusercontent.com/2221289/129941990-9e2ee761-1035-4f5a-9e51-26f7a9446f5a.png)

Okay, so my takeaway is:

- Something is really messed up with the public key mechanism in v10
- The documentation is not even close to an RC state
- Collada cannot be used directly. How on earth does it work for you?
- Migrating MapBox to SwiftUI aka 2021 is a pain in the... but I have to go this route... 😫

**Comment by macdrevx** [comment] 2021-08-18 18:27
Re: Collada -- that's really surprising. Xcode should be processing the file at build time (search for "dae" under Build Rules under the Examples target)

<img width="371" alt="Screen Shot 2021-08-18 at 1 19 16 PM" src="https://user-images.githubusercontent.com/205658/129951219-fef02eb4-fd6e-4100-ac49-9b89ce200002.png">

And if you look in the build log, and select "All" and "All Messages" and then filter for dae, you should even see that the conversion is being run using scntool during the build:

<img width="956" alt="Screen Shot 2021-08-18 at 1 25 29 PM" src="https://user-images.githubusercontent.com/205658/129952012-e9ed572f-149a-46e0-926a-773bf00c579c.png">

Do you see that log? Is there anything there that looks suspicious?

**Comment by MartinMajewski** [comment] 2021-08-18 18:36
Yep, found something very suspicious here:

![Screenshot 2021-08-18 at 20 36 07](https://user-images.githubusercontent.com/2221289/129953460-5ef23519-d7df-4915-84a7-5f36e08329d0.png)

**Comment by MartinMajewski** [comment] 2021-08-18 18:47
Okay, I've found the root cause!

I had to go to Xcode -> Preferences -> Locations and reselect the "Command Line Tools" in the dropdown menu.
Afterward, I changed `withExtension` to dae again and cleaned the build output folder (Shift - CMD - K). After rebuilding the space antenna stood upright and the dae was converted correctly... puh!

**Comment by MartinMajewski** [comment] 2021-08-18 18:48
So, now I want to know why my public key is not getting picked up correctly from .mapbox nor the plist file... ;-)

**Comment by macdrevx** [comment] 2021-08-19 13:44
Great, glad we could get to the bottom of the original issue.

Re: documentation out of date — this is my fault. I linked you to the wrong page. We actually do have an up-to-date page for v10: https://docs.mapbox.com/ios/beta/maps/guides/install/

Let's track the other things in separate issues…

* Public key management: https://github.com/mapbox/mapbox-maps-ios/issues/606
* SwiftUI — could you open a new issue that describes your use case and what you'd like to see from Maps SDK?

**Comment by MartinMajewski** [comment] 2021-08-19 14:14
I will open the SwiftUI issue. I think these are all the topic for now.

Thanks for the support.

**Closed** 2021-08-19 17:52 UTC
Labels: bug :beetle:, p1
