### ISSUE TITLE
withViewportAnimation on viewport = .camera 

### ISSUE THREAD

**Issue by david-buck** [mapbox/mapbox-maps-ios#2047] opened 2023-11-05 10:43 UTC
## Environment

Xcode version: 15.0.1
iOS version: 17.0.1
Devices affected: simulator vs device
Maps SDK Version: 11.0.0-rc.1

## Observed behavior and steps to reproduce

I have a button in my app that will recenter the map. The function is basically:

```
    func recenterMap() {
        isProgrammaticUpdate = true
        
        if let liveUpdate = liveUpdate {
            withViewportAnimation(.easeOut(duration: 0.5)) {
                viewport = .camera(center: CLLocationCoordinate2D(latitude: liveUpdate.update.position.latitude, longitude: liveUpdate.update.position.longitude))
                    .inset(by: insets)
            } completion: { _ in
                DispatchQueue.main.async {
                    self.isProgrammaticUpdate = false
                }
            }
        }
    }
```
            
In the simulator, I can trigger this function and it will cancel any other transition or panning that is happening and animate back to the centre point.

On my iPhone, unless the map is idle, the transition isn't animated, and any momentum the map had from being dragged continues once the map has jumped back to the centred point. 

## Expected behavior

I would think that the behaviour I am seeing in the simulator would be the behaviour on device; a new viewport animation should cancel all other transitions and run until it is completed or interrupted.

### From iPhone
https://github.com/mapbox/mapbox-maps-ios/assets/5119820/1b821ca5-a955-4959-be7b-20d71d308582

### From Simulator

https://github.com/mapbox/mapbox-maps-ios/assets/5119820/3bf9b178-c7b2-4154-855b-5f997da60270

**Comment by persidskiy** [comment] 2023-11-07 14:49
Hi @david-buck , thanks for the report! I didn't manage to reproduce it, could you please provide a bare minimum example that reproduces the bug?
Also, do you run the latest `11.0.0-rc.1` version on both iPhone and Simulator? We had an issue that viewport didn't reset to `idle` upon very quick drag interaction, that might be the reason for the behavior you see. But this issue was fixed in rc.1.

**Comment by david-buck** [comment] 2023-11-10 03:21
Thanks @persidskiy . I have started to create a simple reproduction to see where the issue is coming up. All signs seem to be pointing to a conditional state update in `.onCameraChanged` . Hopefully I either work out how to solve my problem, or how to simply recreate it. Either way, I'll keep you posted.

**Comment by persidskiy** [comment] 2023-12-14 11:44
@david-buck Thank you for the feedback, the api for listening to those events was missing in SwiftUI. It will be fixed in one of the upcoming releases with https://docs.tilestream.net/ios/maps/api/latest/documentation/mapboxmaps/map/gesturehandlers(_:), you can try the fresh `main` branch version

**Closed by persidskiy** 2023-12-14 11:44 UTC
Labels: bug :beetle:, SwiftUI
