### ISSUE TITLE
Viewannotations are not in sync with the camera

### ISSUE THREAD

**Issue by latargere** [mapbox/mapbox-maps-ios#979] opened 2021-12-25 17:31 UTC
## Environment

- Xcode version: 13.2
- iOS version: 15.2
- Devices affected: iPhone 13 pro
- Maps SDK Version: 10.2

## Observed behavior and steps to reproduce

the latest mapbox sdk introduced the view annotation which is really great for our needs but this new annotation is not in sync with the camera and other layers when we move the map

## Expected behavior

Be in sync with the camera like layers.

## Additional links and references

`

https://user-images.githubusercontent.com/7023805/147390364-9daf7473-a790-4562-99de-2363444187fa.MOV

`

**Comment by jvanakker** [comment] 2021-12-27 14:32
I can confirm the same problem.

**Comment by mathipalm** [comment] 2021-12-29 16:59
Can confirm as well, same problem for me

**Comment by Eke** [comment] 2022-01-04 12:12
Same here

**Comment by himu243** [comment] 2022-01-05 06:11
I can also confirm the same. Looks like a bug

**Comment by kiryldz** [comment] 2022-01-07 07:49
Thanks for the feedback on that new feature!

This behaviour is not a bug as view annotations are actual regular `UIView`s drawn on top of the map surface rendered by Metal - that causes small visual delay when moving the map. @macdrevx could you please provide more iOS technical background if needed and correct if I'm wrong 😄 Perhaps we could think of something to at least reduce it from our end.

However looking at the issue itself for me it seems that if layout is pretty simple like in this case (just showing distance) and ideal map + view synchronization is critical - you could point annotations to add such icons directly to the map, see e.g. this [example](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/MultiplePointAnnotationsExample.swift). In that case that view will be rendered as part of the map. I'm an Android dev but for me it seems that it should be [possible](https://www.hackingwithswift.com/example-code/media/how-to-render-a-uiview-to-a-uiimage) to even build some `UIView` and convert it to `UIImage` and then set as an icon to point annotation manager.

**Comment by latargere** [comment] 2022-01-12 17:45
Thanks for the answer.
Yes for this kind of easy layout we could create an image but for view that will need some animation, it will not possible to just snapshot the view. For example, if we want to nicely react to zoom level or other map events.
The same issue appears with the courseview from Mapbox Navigation when you interact with the map

**Comment by macdrevx** [comment] 2022-01-14 15:01
Hi all, there's an option on `MapView` called `presentsWithTransaction` (corresponding to the property of the same name on the underlying Metal view) that may help with this. Could you try setting it to `true` to see whether that improves the situation?

https://docs.mapbox.com/ios/maps/api/10.2.0/Classes/MapView.html#/s:10MapboxMaps7MapViewC23presentsWithTransactionSbvp

**Comment by latargere** [comment] 2022-01-19 15:04
I tried but still the same problem

**Comment by johnnewman** [comment] 2022-01-27 18:08
Switching `presentsWithTransaction` between true and false doesn't seem to change the behavior for me either. View-based annotations still lag behind the style layer annotations as the camera moves.

Here's my setup: Xcode 13.2.1, iPhone 12 Pro, iOS 15.2.1, Mapbox Maps 10.2.0

**Comment by macdrevx** [comment] 2022-01-27 18:14
Thanks for checking. We'll have to dig in to this a bit more to see what can be done.

**Comment by timbalzer** [comment] 2022-05-06 01:08
Can confirm same problem here.

**Comment by julianrex** [comment] 2022-05-17 15:19
Drive-by comment @macdrevx @kiryldz: IIRC for synchronization we needed both `presentsWithTransaction` *and* to trigger the rendering with `setNeedsDisplay`. There was a bug in iOS 14 that blocked the display (with waiting for drawables) which IIRC [we needed to fix with `setNeedsDisplay`](https://github.com/mapbox/mapbox-gl-native-ios/pull/411). This was OpenGL (but that sits on top of Metal anyway), and we were able to repro with raw Metal too. IIRC we tried without for `mapbox-maps-ios`, but still ended up having rendering issues with one particular device type (I think it was iPad on iOS 15 maybe?. Perhaps @knov will remember).

IIRC input latency wasn't too bad with `setNeedsDisplay`, but I still feel a dedicated render thread would allow you to trigger rendering closer to the vsync.

**Comment by kiryldz** [comment] 2022-07-22 10:45
Hey all, could you please let me know if behaviour has become better with `presentsWithTransaction` when using https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.7.0-beta.1? We did refactor core view annotation placement logic.

**Comment by evil159** [comment] 2022-08-11 12:14
Hopefully `presentsWithTransaction` helped, I'm closing this ticket for now, feel free to reopen if you still experiencing this issue. We are planning to make a change to prevent view annotations being out of sync with map updates altogether in upcoming releases. Stay tuned!

**Closed by evil159** 2022-08-11 12:14 UTC
Labels: bug :beetle:

**Comment by johnnewman** [comment] 2022-08-15 14:19
Thank you for looking into this bug. I've tried `presentsWithTransaction` with MapboxMaps 10.7.0 and the behavior is much better. I don't see view-based annotations lagging behind the camera anymore!

I'm using Xcode 13.4.1 with an iPhone 12 Pro running iOS 15.6.

**Comment by milan121** [comment] 2023-07-08 10:53
i have same issue in android. i'm using mapbox v10.14.0, how can i solve it

**Comment by milan121** [comment] 2023-07-08 10:53
> 

hi you have found any solution for this
