### ISSUE TITLE
Is it okay to release a new beta that doesn't even compile?

### ISSUE THREAD

**Issue by jeudesprits** [mapbox/mapbox-maps-ios#165] opened 2021-03-06 13:48 UTC
## Environment

- Xcode version: Version 12.4 (12D4e)
- iOS version: 14.4
- Devices affected: All
- Maps SDK Version: 10.0.0-beta.15

## Swift Compiler Error Group:

**.../SourcePackages/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Foundation/Extensions/Core/MapEvents.swift:50:28: Type 'MapEvents' has no member 'cameraChanged'**

**.../SourcePackages/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Foundation/Extensions/Core/MapEvents.swift:86:34: Type 'MapEvents' has no member 'cameraChanged'**

**.../SourcePackages/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Foundation/BaseMapView.swift:125:64: Extra argument 'pixelRatio' in call**

**.../SourcePackages/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Foundation/BaseMapView.swift:119:52: Missing argument for parameter '__mapMode' in call**

## Warning Group:

**Skipping duplicate build file in Copy Files build phase: .../SourcePackages/artifacts/MapboxCommon/MapboxCommon.xcframework/ios-arm64_i386_x86_64-simulator/MapboxCommon.framework**

**Comment by macdrevx** [comment] 2021-03-07 18:14
Hi @jeudesprits, thanks for sharing this with us. The warning you reported is on our radar and will be resolved in an upcoming release. It does not cause any problems at runtime.

As for the errors, I'm unable to reproduce them locally. I've noticed that sometimes when upgrading packages in Xcode, I need to reset the cache. Could you try that and see whether it resolves these issues? You can do it in Xcode by navigating to File > Swift Packages > Reset Package Caches.

After you do that, you should see the following package versions installed:

<img width="262" alt="Screen Shot 2021-03-07 at 12 13 12 PM" src="https://user-images.githubusercontent.com/205658/110249980-8c17c500-7f3e-11eb-9c76-81e093ba4e20.png">

Please let us know if that fixes things for you.

**Comment by alberussoftware** [comment] 2021-03-12 11:13
@macdrevx Fixed

**Closed** 2021-03-12 14:28 UTC
Labels: bug :beetle:
