### ISSUE TITLE
Crash in PinchGestureHandler

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#1074] opened 2022-01-30 23:42 UTC
## Environment

- Xcode version: 13.2
- iOS version: 15.2.1
- Devices affected: iPhone XR
- Maps SDK Version: 10.1.0

I got the following crash reported through Crashlytics from a user device:

Fatal Exception: NSRangeException
-[UIPinchGestureRecognizer locationOfTouch:inView:]: index (1) beyond bounds (1).

4
MapboxMaps
PinchGestureHandler.swift - Line 147
PinchGestureHandler.handleGesture(_:) + 147

That points to the line I've commented:

    private func pinchAngle(with gestureRecognizer: UIPinchGestureRecognizer) -> CGFloat {
        // we guard for this at the call site
        let view = gestureRecognizer.view!
        let pinchPoint0 = gestureRecognizer.location(ofTouch: 0, in: view)
        let pinchPoint1 = gestureRecognizer.location(ofTouch: 1, in: view)  // ***HERE
        return angleOfLine(from: pinchPoint0, to: pinchPoint1)
    }

**Comment by macdrevx** [comment] 2022-01-31 00:35
We believe this is fixed in 10.2

**Comment by macdrevx** [comment] 2022-01-31 00:37
Duplicate of https://github.com/mapbox/mapbox-maps-ios/issues/833

**Closed** 2022-01-31 15:15 UTC
Labels: bug :beetle:
