### ISSUE TITLE
Custom style URL makes layers blurred

### ISSUE THREAD

**Issue by LearnWithTung** [mapbox/mapbox-maps-ios#1097] opened 2022-02-08 07:43 UTC
## Environment

- Xcode version: 13.2.1
- iOS version: 15.0
- Devices affected: simulators and devices
- Maps SDK Version: 10.2.0

## Observed behavior and steps to reproduce
I'm using the same custom map style URL for both v6 and v10
But the shapes look blurred and broken but it works fine on v6
You can see image bellow from v10:
![IMG_4299](https://user-images.githubusercontent.com/61558556/152940567-941e3bb8-3fdd-4591-8a58-25099effe6cd.jpg)

If I use build-in style such as `.light` it also looks fine

**Comment by ZiZasaurus** [comment] 2022-02-08 17:13
@LearnWithTung, can you please provide the style URL, access to the style, and the coordinates where you notice the blurriness so that I can reproduce this behavior? Have you tested with other styles?

**Comment by LearnWithTung** [comment] 2022-02-09 03:58
Hi @ZiZasaurus 
The URL is here: mapbox://styles/valeria508/ck37qapgh0ge81coz3f23gnuc
I've created a new style and it works fine. Does that mean the problem relies on my URL ? But how does a map style can effect the quality of rendered layers, addition the URL works fine on v6.

**Comment by ZiZasaurus** [comment] 2022-02-09 22:37
@LearnWithTung are those shapes coming from the style? I'm not seeing them when I use your styleURL.

**Comment by tungvustarglobal** [comment] 2022-02-10 06:49
No it's not, the shapes are from API. I've extracted an example here
https://drive.google.com/file/d/1hPPqxl3K97ZuVXUAhuMx02sjmd40faBQ/view?usp=sharing

**Comment by LearnWithTung** [comment] 2022-02-10 06:50
No it's not, the shapes are from API. I've extracted an example here
https://drive.google.com/file/d/1hPPqxl3K97ZuVXUAhuMx02sjmd40faBQ/view?usp=sharing

**Comment by LearnWithTung** [comment] 2022-02-10 09:07
Here's my code
```
    var source = GeoJSONSource()
    source.data = .featureCollection(.init(features: features))

    var poligonLayer = FillLayer(id: namePrefix + Constans.ShapesID.fill)
    poligonLayer.source = identifier
    poligonLayer.fillColor = .constant(.init(shapeColor))

    var borderLayer = LineLayer(id: namePrefix + Constans.ShapesID.border)
    borderLayer.source = identifier
    borderLayer.lineJoin = .constant(.round)
    borderLayer.lineColor = .constant(.init(borderColor))
    
    borderLayer.lineOpacity = poligonLayer.fillOpacity
    borderLayer.lineWidth = .expression(Exp(.interpolate) {
      Exp(.linear)
      Exp(.zoom)
      Constans.Stops.borderLineWidth
    })
```

**Comment by LearnWithTung** [comment] 2022-02-14 03:22
Have you tried ?

**Comment by ZiZasaurus** [comment] 2022-02-14 23:16
@LearnWithTung, I am unable to reproduce with the data you provided as it does not appear to be a valid json. If I add my own data, however, it appears with no blurriness.

**Comment by LearnWithTung** [comment] 2022-02-15 02:56
```
            let path = Bundle.main.path(forResource: "data", ofType: "json")!
            let data = FileManager.default.contents(atPath: path)!
            let features = try! JSONSerialization.jsonObject(with: data) as! [String: Any]

            var source = try! GeoJSONSource(jsonObject: features)
                        
            let identifier = "noParking" + "Constans.ShapesID.source"
            var poligonLayer = FillLayer(id: "noParking" + "fillShapeLayer")
            poligonLayer.source = identifier
            poligonLayer.fillColor = .constant(.init(.clear))
            
            var borderLayer = LineLayer(id: "noParking" + "shapeBorderLayers")
            borderLayer.source = identifier
            borderLayer.lineJoin = .constant(.round)
            borderLayer.lineColor = .constant(.init(.red))
            
            borderLayer.lineOpacity = poligonLayer.fillOpacity
            borderLayer.lineWidth = .expression(Exp(.interpolate) {
                Exp(.linear)
                Exp(.zoom)
                16
                0.5
                22
                3
            })
            borderLayer.lineWidth = .constant(2)
            
            let style = self.mapView.mapboxMap.style
            try? style.addSource(source, id: identifier)
            try? style.addLayer(poligonLayer, layerPosition: nil)
            try? style.addLayer(borderLayer, layerPosition: nil)
            let path = Bundle.main.path(forResource: "data", ofType: "json")!
            let data = FileManager.default.contents(atPath: path)!
            let features = try! JSONSerialization.jsonObject(with: data) as! [String: Any]

            var source = try! GeoJSONSource(jsonObject: features)
                        
            let identifier = "noParking" + "Constans.ShapesID.source"
            var poligonLayer = FillLayer(id: "noParking" + "fillShapeLayer")
            poligonLayer.source = identifier
            poligonLayer.fillColor = .constant(.init(.clear))
            
            var borderLayer = LineLayer(id: "noParking" + "shapeBorderLayers")
            borderLayer.source = identifier
            borderLayer.lineJoin = .constant(.round)
            borderLayer.lineColor = .constant(.init(.red))
            
            borderLayer.lineOpacity = poligonLayer.fillOpacity
           borderLayer.lineWidth = .expression(Exp(.interpolate) {
                Exp(.linear)
                Exp(.zoom)
                16
                0.5
                22
                3
            })
            
            let style = self.mapView.mapboxMap.style
            try? style.addSource(source, id: identifier)
            try? style.addLayer(poligonLayer, layerPosition: nil)
            try? style.addLayer(borderLayer, layerPosition: nil)
```
That's weird. I'm using the data I've sent you. Please review the code above.

**Comment by ZiZasaurus** [comment] 2022-02-15 18:40
@LearnWithTung ah thank you, I've got it now, and am able to see slight blurriness. In your original style, can you update your supported JS, iOS and Android versions to match the supported SDK version of the default style: Javascript: 2.6.0, iOS: 10.0.0, Android: 10.0.0. Once you do this, can you wait about 10 minutes and then try to display your map style with the geometries added and see if the blurriness is still visible?

Below is a screenshot of the difference between your style's supported SDK versions and the default style's: 
![Screen Shot 2022-02-15 at 1.35.00 PM.png](https://images.zenhubusercontent.com/5d9f907d89616e000103e95c/8f4a708a-3e69-4546-84d5-be721dd0c7cc)

**Comment by ZiZasaurus** [comment] 2022-02-21 18:31
@LearnWithTung closing this ticket. Please feel free to reopen if you have additional questions or your issue was not resolved.

**Closed by ZiZasaurus** 2022-02-21 18:31 UTC
Labels: bug :beetle:
