### ISSUE TITLE
Invalid privacy manifest

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#2145] opened 2024-03-14 18:52 UTC
I just submitted my app for Apple review, and I got the following back.  That version of the app includes version 11.1.0 of the Mapbox SDK.  Was this already fixed in 11.2.0?

> ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/MapboxCommon.framework/PrivacyInfo.xcprivacy”. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app’s privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

There were also several references to "ITMS-91053: Missing API declaration", but I can't tell which of these are from Mapbox, and which from other code.  But here they are in case they're useful:

> ITMS-91053: Missing API declaration - Your app’s code in the “Peakbagger” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the “Peakbagger” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategorySystemBootTime. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the “Peakbagger” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryDiskSpace. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
> 
> ITMS-91053: Missing API declaration - Your app’s code in the “Peakbagger” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.
>

**Comment by sebarina** [comment] 2024-03-15 03:19
We received the same Email after submitting a testflight version

**Comment by bryanmalaluan** [comment] 2024-03-18 01:01
We also receive the same email earlier today

**Comment by marcoboerner** [comment] 2024-03-18 08:34
+1 Received an email with the same first paragraph and two warnings, referring to our app for `NSPrivacyAccessedAPICategoryFileTimestamp` and `NSPrivacyAccessedAPICategorySystemBootTime`. However, it seems those come from Mapbox or another dependency Mapbox uses.

**Comment by persidskiy** [comment] 2024-03-18 14:22
@akirmse Thank you for reporting the issue, we are working on it.

**Comment by hexadecy** [comment] 2024-03-20 20:52
I hope it will be backported to v10.

The v11 needs iOS 13 because of this bug in this wrapper for React-Native: https://github.com/rnmapbox/maps/issues/2607

**Comment by persidskiy** [comment] 2024-03-22 13:03
@akirmse @bryanmalaluan @marcoboerner Hi, can you try to upload the build again, using the 11.2.0 version? 

I've tried to upload the bare bone iOS app using the Maps SDK and don't see any of those errors.

**Comment by persidskiy** [comment] 2024-03-22 13:03
Also, do you use the Navigation SDK?

**Comment by akirmse** [comment] 2024-03-22 15:45
It will probably be another week or two before I have a build ready to submit.  I don't use the Navigation or Search SDKs.

**Comment by cixio** [comment] 2024-03-22 16:01
> I've tried to upload the bare bone iOS app using the Maps SDK and don't see any of those errors.

you need to submit for review then you instantly get an email with the messages above.

**Comment by james-wag** [comment] 2024-03-22 21:40
It appears the Mapbox frameworks need to add a `PrivacyInfo.xcprivacy` file and add the 2 Keys to it explaining what the system boot time and file creation date APIs it's using are for. See https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by connorpmullins** [comment] 2024-03-26 20:47
Hopping into this comment thread to say that v10 seems to have a PrivacyInfo.xcprivacy file starting with 10.16.1:
https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.16.1

**Comment by connorpmullins** [comment] 2024-03-26 21:23
No, actually I must be wrong about the root cause. Looking at our MapboxCommon framework,  the PrivacyInfo.xcprivacy file is present. The error message specifically states `ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: "Frameworks/MapboxCommon.framework/PrivacyInfo.xcprivacy"`.

So either the file format is incorrect or the path is incorrect, but the file is present. I don't which is more likely.

@persidskiy - I just want to chime in to say that we desperately need v10 support for this as we have 3rd party dependencies that are not yet Mapbox v11 compatible.

**Comment by persidskiy** [comment] 2024-03-28 15:31
The fix is released in the new [`11.3.0-rc.1`](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.3.0-rc.1)

The v10 release with the fix is planned for the next week.

**Comment by connorpmullins** [comment] 2024-03-28 15:52
Thank you!! 🙇

**Comment by persidskiy** [comment] 2024-04-03 12:19
Hi all, the [`10.17.0`](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.17.0) with the fix is released.

I am closing the issue. Please reopen if you encounter similar issues.

**Closed by persidskiy** 2024-04-03 12:19 UTC
Labels: bug :beetle:

**Comment by fractalscape13** [comment] 2024-04-03 15:48
does this resolve the issue for rnmapbox ?

**Comment by JackJBlundell** [comment] 2024-05-05 00:03
For anybody experiencing this using MapboxNavigation, make sure you use 2.18! 

```
MapboxNavigation", "~> 2.18"
```

To your podfile.

**Comment by AndrewGable** [comment] 2024-05-06 18:24
Can anyone link the commit or fix for this? I was having trouble finding it in the release diff. 

We are suddenly seeing an "invalid binary" when uploading to App Store Connect and use a bespoke solution that is blocked on updating SDK versions. Thank you 🙏

**Comment by mn288** [comment] 2024-05-07 07:28
@persidskiy version 11.2.0 just popped with this error today too... care to extend the fix for this version too as we can't yet update to version 11.3.0 with its breaking changes.

**Comment by tPiffrader** [comment] 2024-05-08 13:24
@persidskiy How about `MapboxSearch` ? I am using version `2.0.1` and get this message from apple:
```ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/MapboxCoreSearch.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn‘t empty. Keys and values in your app’s privacy manifest must be valid.```

**Comment by santoso8118** [comment] 2024-05-09 05:06
Hi @JackJBlundell  :
I am currently using MapboxNavigation version 2.17.0, it's linked to mapbox-maps-ios to 10.16.4 now. 
Can I just upgrade dependency of mapbox-maps-ios to 10.17.0 without upgrade MapboxNavigation 2.18? 

Does MapboxNavigation 2.17.0 compatible with mapbox-maps-ios to 10.17.0 ?
If it not compatible. Is there any way to fix this issue in mapbox-maps-ios to 10.16.4?

**Comment by git-jr** [comment] 2024-05-23 14:27
You did it? It worked?

**Comment by santoso8118** [comment] 2024-05-24 03:11
yes @git-jr It worked

**Comment by git-jr** [comment] 2024-07-05 19:14
Hi!
Solution of [santoso8118](https://github.com/santoso8118) work here, but we changed the version to 10.1.24

![image](https://github.com/mapbox/mapbox-maps-ios/assets/35709152/4adbcd3b-4b23-4286-9aaf-e67203a2af5b)
