### ISSUE TITLE
Mapbox Navigation and Mapbox Search for iOS SDK not installing "CocoaPods could not find compatible versions for pod "MapboxCommon""

### ISSUE THREAD

**Issue by szewah** [mapbox/mapbox-maps-ios#472] opened 2021-06-14 15:43 UTC
## Environment

- Xcode version: 12.5
- iOS version:  14.0
- Maps SDK Version:  6.3.0

## Observed behavior and steps to reproduce

Following lines for Mapbox Map, Mapbox Search, Mapbox Navigation added

<img width="679" alt="podfile" src="https://user-images.githubusercontent.com/32065713/121919089-aa8f1880-cd04-11eb-8d85-6a4ad6418b52.png">

`pod repo update && pod install`

### Result

`[!] CocoaPods could not find compatible versions for pod "MapboxCommon":
  In Podfile:
    MapboxNavigation (~> 1.3) was resolved to 1.3.0, which depends on
      MapboxCoreNavigation (= 1.3.0) was resolved to 1.3.0, which depends on
        MapboxNavigationNative (~> 31.0) was resolved to 31.0.1, which depends on
          MapboxCommon (= 9.2.0)

    MapboxSearch (< 2.0, >= 1.0.0-beta.3) was resolved to 1.0.0-beta.5, which depends on
      MapboxCommon (~> 9.0.0)`

## Expected behavior

Pods install

**Comment by knov** [comment] 2021-06-14 16:26
cc @mapbox/navigation-ios @mapbox/search-sdk-ios

**Comment by S2Ler** [comment] 2021-06-15 05:58
The problem is that `MapboxSearch` is too strict in their dependency on `MapboxCommon`:  `s.dependency "MapboxCommon", "~> 9.0.0"`. 

`~> 9.0.0` means that they will only work with versions from `9.0.0` up to `9.1.0` excluding `9.1.0`. 

@mapbox/search-sdk-ios Is it possible to lower MapboxComman version restrictions by changing from `~> 9.0.0` to ``~> 9.0`?

**Comment by S2Ler** [comment] 2021-06-15 13:01
Update: `MapboxSearch` 1.0 and `MapboxNavigation` 1.3-1.4 are not compatible.

**Comment by S2Ler** [comment] 2021-06-16 06:29
@knov I would close this ticket as there is nothing we are planing to do about that. It is just incompatible configuration for our SDKs.

**Closed** 2021-06-17 19:50 UTC
Labels: bug :beetle:

**Comment by JacopoKenzo** [comment] 2021-06-27 05:21
Having the same issue. Should we wait for an update of MapboxSearch?
Or MapboxSearch and MapboxNavigation will never work together?

**Comment by S2Ler** [comment] 2021-06-27 06:25
NavigationSDK 2.0 (currently in beta) works with MapboxSearch.

**Comment by JacopoKenzo** [comment] 2021-06-27 07:24
Thanks @S2Ler !

I'm currently running these versions in an experimental project:
`  pod 'MapboxMaps', '10.0.0-rc.2'
    
    pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v2.0.0-beta.15'
    pod 'MapboxNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v2.0.0-beta.15'`

But I can't find a way to install MapboxSearch (or MapboxSearchUI). Is it possible?

**Comment by S2Ler** [comment] 2021-06-27 10:07
@JacopoKenzo checkout this guide https://docs.mapbox.com/ios/search/guides/install/

**Comment by JacopoKenzo** [comment] 2021-06-27 13:48
@S2Ler Thanks for sharing! I did follow that and anything else related I could find.

As you said above looks like `MapboxSearch` is too strict in their dependency on `MapboxCommon`

```MapboxNavigation (from `https://github.com/mapbox/mapbox-navigation-ios.git`, tag `v2.0.0-beta.15`) was resolved to 2.0.0-beta.15, which depends on
      MapboxMaps (= 10.0.0-rc.2) was resolved to 10.0.0-rc.2, which depends on
        MapboxCoreMaps (= 10.0.0-rc.2) was resolved to 10.0.0-rc.2, which depends on
          MapboxCommon (~> 14.0.1)
MapboxSearch (< 2.0, ~> 1.0.0-beta.5) was resolved to 1.0.0-beta.5, which depends on MapboxCommon (~> 9.0.0)```

I don't think is currently possible to install `MapboxSearch` using `Mapbox SDK v10`

**Comment by S2Ler** [comment] 2021-06-28 09:58
@JacopoKenzo Thanks for reporting! @mapbox/search-sdk-ios will fix this issue so that `MapboxSearch SDK for iOS` will be compatible with `MapboxNavigation v2.0.0-beta.15`. Stay tuned!

**Comment by JacopoKenzo** [comment] 2021-06-28 10:07
@S2Ler Awesome! I'll try to hold on! :)

**Comment by zugaldia** [comment] 2021-06-28 15:47
> Or MapboxSearch and MapboxNavigation will never work together?

Just to set the record straight, the opposite is true. Naturally, our goal is to make all Mapbox SDKs compatible so that you can pick the right product combination for your project. If you find more incompatibilities like this one in the future, please continue reporting them. Thanks!

**Comment by JacopoKenzo** [comment] 2021-06-29 13:31
@zugaldia That was my thought, I see what you guys are doing with all the new SDKs.. and I'm impressed on how responsive you guys are on Github! Keep up the good work!

Where is the best place to follow Search SDK updates? The repo is not public like Navigation / Directions / Maps SDK. Thanks!

**Comment by kalbaxa** [comment] 2021-06-29 14:54
Engineering Manager of Search SDK speaking:

@JacopoKenzo Thank you for showing interest and following our progress.

@zugaldia is correct. We do plan for all SDKs to work seamlessly together in any combination.

For Search SDK - docs and examples are the only options to track until we go open source with the platform Search SDKs. We do plan to do that but I don't have the public timeline yet.

We keep the [docs updated](https://docs.mapbox.com/api/search/) and we also have examples for [iOS](https://github.com/mapbox/search-ios-examples) and [Android](https://github.com/mapbox/mapbox-search-android-examples).

**Comment by JacopoKenzo** [comment] 2021-07-03 10:10
Update: Successfully updated to the latest SDKs!

```
Installing MapboxCommon 14.2.0 (was 14.0.1)
Installing MapboxCoreMaps 10.0.0-rc.3 (was 10.0.0-rc.2)
Installing MapboxCoreNavigation 2.0.0-beta.16 (was 2.0.0-beta.15)
Installing MapboxGeocoder.swift (0.10.2)
Installing MapboxMaps 10.0.0-rc.3 (was 10.0.0-rc.2)
Installing MapboxNavigation 2.0.0-beta.16 (was 2.0.0-beta.15)
Installing MapboxNavigationNative 55.0.0 (was 54.0.0)
Installing MapboxSearch (1.0.0-beta.7)
```

First step ✅ 
Thank you guys!
