### ISSUE TITLE
Ability to use Two fingers to both Pan as well as Zoom in/out

### ISSUE THREAD

**Issue by dmiluski** [mapbox/mapbox-maps-ios#508] opened 2021-06-30 14:51 UTC
## New Feature

When using two fingers a user should be able to both pan as well as zoom in and out at the same time.

SDK: 

```
      {
        "package": "MapboxCommon",
        "repositoryURL": "https://github.com/mapbox/mapbox-common-ios.git",
        "state": {
          "branch": null,
          "revision": "16e7bb71288b7835e420ba8213c1c45276338839",
          "version": "13.0.0"
        }
      },
      {
        "package": "MapboxCoreMaps",
        "repositoryURL": "https://github.com/mapbox/mapbox-core-maps-ios.git",
        "state": {
          "branch": null,
          "revision": "b293ea5976b2b91d8aceff8096e24107de94afad",
          "version": "10.0.0-beta.23"
        }
      },
      {
        "package": "MapboxDirections",
        "repositoryURL": "https://github.com/mapbox/mapbox-directions-swift.git",
        "state": {
          "branch": null,
          "revision": "c2bfe34699721f1fbdb2a31fb62f00b036ffb248",
          "version": "2.0.0-beta.3"
        }
      },
      {
        "package": "MapboxMobileEvents",
        "repositoryURL": "https://github.com/mapbox/mapbox-events-ios.git",
        "state": {
          "branch": null,
          "revision": "8e0c725271dee0a0c957b9b9738aef81b601f12b",
          "version": "1.0.2"
        }
      },
      {
        "package": "MapboxMaps",
        "repositoryURL": "https://github.com/mapbox/mapbox-maps-ios.git",
        "state": {
          "branch": null,
          "revision": "ccf4cc26db8c7ace9b45fa72a5020c56ad0d0c30",
          "version": "10.0.0-beta.21"
        }
      },
      {
        "package": "MapboxNavigation",
        "repositoryURL": "https://github.com/mapbox/mapbox-navigation-ios",
        "state": {
          "branch": null,
          "revision": "c2ea1e2d8c237c31784b6cb999a64dfb8d4a8f77",
          "version": "2.0.0-beta.14"
        }
      },
      {
        "package": "MapboxNavigationNative",
        "repositoryURL": "https://github.com/mapbox/mapbox-navigation-native-ios.git",
        "state": {
          "branch": null,
          "revision": "3b748e2105b8358d000943d27493ca8559ae0a47",
          "version": "52.0.0"
        }
      },
```

## Why

While toying with the map, I noticed if I used two fingers to begin interacting with the map, the only action I can make is to zoom in and out. Panning gestures do not move the map. It is possible to both pan/zoom if I start with 1 finger then add a second finger, but impossible if I start with two.

This is possible on both Apple/Google Maps

**Comment by cmilack** [comment] 2021-06-30 14:55
Duplicate of #474

**Comment by neelmistry94** [comment] 2021-09-01 21:48
@dmiluski I can confirm that this has been fixed and released a while ago. Please try the latest RC version of maps and let us know the issue persists. If not, please close this ticket

**Comment by dmiluski** [comment] 2021-09-01 21:49
Thanks @neelmistry94 . This is fine to close then

**Closed** 2021-09-01 21:54 UTC
