### ISSUE TITLE
Add ability to set a threshold for rotation while zooming, and improve nording the map

### ISSUE THREAD

**Issue by georgbachmann** [mapbox/mapbox-maps-ios#1076] opened 2022-01-31 15:38 UTC
## New Feature

My "problem" is that I can't zoom my map without having at least a little bit of rotation. That in my opinion makes the zooming-experience not that great. I could of course disable rotation, but I don't want that...

The old version of Mapbox had the ability to set ability to set `MGLRotationThresholdWhileZooming`. Developers where able to set it as a UserDefault and it was a value in `degrees`.
That was perfekt. I could set it to something like 20°, so you don't accidentally rotate if all you want is zooming (which will most likely by like >90% of the time what I want)

Also... the old version had some haptic feedback when you were rotated and then rotate back to the map being norded (now sure if that is an english word... but I mean the map rotated at 0° -> north being straight on top)... I liked that as an indicator when I am back...

And... while I am here wishing things... It would be nice if the map would snap to north, if you are quite close. The old version also did that. So when I am rotated before and then rotate back to something quite close to north, it would just snap there. I know that tapping the compass also does that, but the map helping me do what I most likely want would be super handy...

**Comment by ZiZasaurus** [comment] 2022-02-01 14:03
@geogbachmann, closing as a duplicate of https://github.com/mapbox/mapbox-maps-ios/issues/755.

**Closed by ZiZasaurus** 2022-02-01 14:03 UTC
