### ISSUE TITLE
Inconsistencies in CustomLayerHost render(parameters:mtlCommandBuffer:mtlRenderPassDescriptor) calls

### ISSUE THREAD

**Issue by Cal-um** [mapbox/mapbox-maps-ios#513] opened 2021-06-30 19:30 UTC
## Environment

- Xcode version:12.5.1
- iOS version:14.5
- Devices affected: sims + device
- Maps SDK Version: v10.0.0-rc.2

## Observed behavior and steps to reproduce

CustomLayerHost Render delegate method is called continuously after double tap zooming.

- Open CustomLayerExample.swift and breakpoint in the render method (e.g. line 105) or print something on this line.
- Run and open custom layer example
- drag map and observe render calls when dragging and stopping when dragging is finished.
- now double tap to zoom and observe render calls never end after animation is finished.

## Expected behavior

Im not sure what the expected behavior should be. Render calls 60ps or only when it needs to.

I discovered this trying to make a metal node animate and noticed it only works when after double tap zooming. Is there a way to control the frames to make it render continuously as it does when double tapping as above? e.g. control the render by a displayLink?

**Comment by macdrevx** [comment] 2021-06-30 19:53
Possible duplicate of #469. @Cal-um we've just released v10.0.0-rc.3 — could you retest on that version?

**Comment by Cal-um** [comment] 2021-07-01 07:03
Checked and all good now.

Do you know of way to control the number of renders when the map is idle? I need to control it to make animation work in the metal custom layer.

**Comment by Cal-um** [comment] 2021-07-01 12:40
@macdrevx fwiw I found a solution and added a feature request https://github.com/mapbox/mapbox-maps-ios/issues/514

**Closed** 2021-07-01 13:23 UTC
Labels: bug :beetle:
