### ISSUE TITLE
Puck pulse usage  CPU over 50 %

### ISSUE THREAD

**Issue by 666bsw** [mapbox/mapbox-maps-ios#1979] opened 2023-06-14 19:08 UTC
- Xcode version: latest
- iOS version:  latest
- Maps SDK Version: 10.13.1

CPU utilization with Puck pulse exceeds 50%
without pulsation 8-15:

**Comment by OdNairy** [comment] 2023-06-16 09:32
Duplicate of https://github.com/mapbox/mapbox-maps-ios/issues/1939

**Closed by OdNairy** 2023-06-16 09:32 UTC
Labels: bug :beetle:
