### ISSUE TITLE
Setting `compass.image` to `nil` does not update UI to default compass image

### ISSUE THREAD

**Issue by naftalibeder** [mapbox/mapbox-maps-ios#1673] opened 2022-10-28 16:59 UTC
## Environment

- Xcode version: 14.1
- iOS version: 16.1
- Devices affected: Simulator
- Maps SDK Version: 10.9.0

## Observed behavior and steps to reproduce

1. Load the map with the compass enabled:

<img width="61" alt="image" src="https://user-images.githubusercontent.com/2423291/198691429-004ab700-d1c6-410c-a518-c6d7cea2facf.png">

2. Set the compass image to a local asset:

```
mapView.ornaments.options.compass.image = UIImage(named: "compass.png")
```

<img width="57" alt="image" src="https://user-images.githubusercontent.com/2423291/198691619-f05719dc-94ec-42a0-bc10-b888bcae2b57.png">

3. Set the compass image back to nil:

```
mapView.ornaments.options.compass.image = nil
```

<img width="57" alt="image" src="https://user-images.githubusercontent.com/2423291/198691641-019d057e-0f2a-4198-b259-7b24e2c71551.png">

## Expected behavior

The compass image should return to the default, shown in step 1.

## Notes / preliminary analysis

I have attempted setting `visibility` to `.hidden` and back to `.visible`, which does not have any effect on the image displayed.

**Comment by ZiZasaurus** [comment] 2022-10-31 18:50
@naftalibeder I followed the steps you provided above to reproduce and am unable to reproduce this behavior. I've included my screenshots below: 

| With Custom Compass | After setting to nil| 
|-------|--------|
|![Simulator Screen Shot - iPhone 12 - 2022-10-31 at 09 25 23](https://user-images.githubusercontent.com/44972592/199086370-a0954ff6-66bf-4854-a8d6-060171786802.png) |![Simulator Screen Shot - iPhone 12 - 2022-10-31 at 09 25 43](https://user-images.githubusercontent.com/44972592/199085997-7054b3f8-e0f1-46f6-9180-5d5907c6df5b.png)|

**Comment by NiwakaDev** [comment] 2022-11-30 03:51
<h2>Environment</h2>
<ul>
<li>Xcode version: 14.1</li>
<li>iOS version: 16.1</li>
<li>Devices affected: Simulator</li>
<li>Maps SDK Version: 10.9.1</li>
</ul>

<h2>Reproducible code</h2>

The following code can reproduce the problem

```
import UIKit
import MapboxMaps

/**
 NOTE: This view controller should be used as a scratchpad
 while you develop new features. Changes to this file
 should not be committed.
 */

final class DebugViewController: UIViewController {

    var mapView: MapView!
    let button: UIButton = {
        let button = UIButton()
        button.backgroundColor = .red
        button.setTitle("toggle", for: .normal)
        button.translatesAutoresizingMaskIntoConstraints = false
        return button
    }()
    override func viewDidLoad() {
        super.viewDidLoad()
        mapView = MapView(frame: view.bounds)
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        view.insertSubview(mapView, at: 0)
        self.view.addSubview(self.button)
        NSLayoutConstraint.activate([
            self.button.centerXAnchor.constraint(equalTo: self.view.centerXAnchor),
            self.button.centerYAnchor.constraint(equalTo: self.view.centerYAnchor),
            self.button.widthAnchor.constraint(equalToConstant: 80),
            self.button.heightAnchor.constraint(equalToConstant: 40),
        ])
        self.button.addTarget(self, action: #selector(buttonTap(sender:)), for: .touchUpInside)
    }
    var flg = false
    @objc func buttonTap(sender: UIButton){
        if self.flg{
            self.mapView.ornaments.options.compass.image = nil
        }else{
            self.mapView.ornaments.options.compass.image = UIImage(named: "triangle")
        }
        self.flg = !self.flg
    }
        
}

```

**Comment by NiwakaDev** [comment] 2022-11-30 03:52
I am addressing to solve this issue now.

**Comment by pjleonard37** [comment] 2023-02-08 18:10
Closing out as resolved due to [this PR](https://github.com/mapbox/mapbox-maps-ios/pull/1766). Thanks for the contribution @NiwakaDev 🎉 !

**Closed by pjleonard37** 2023-02-08 18:10 UTC
Labels: bug :beetle:
