### ISSUE TITLE
Camera Options with altitude and pitch

### ISSUE THREAD

**Issue by RobertGillett** [mapbox/mapbox-maps-ios#1311] opened 2022-05-04 02:41 UTC
## New Feature
Is there a way to set the CameraOptions or FollowPuckViewportStateOptions to focus on a center coordinate with pitch and altitude? 

## Why
I'm creating an app for pilots. I'm trying to create a first-person view from an airplane in the sky.

**Comment by ZiZasaurus** [comment] 2022-07-30 02:43
Closed as a duplicate of https://github.com/mapbox/mapbox-maps-ios/issues/1282

**Closed by ZiZasaurus** 2022-07-30 02:43 UTC
