### ISSUE TITLE
MapboxMap.point(for: CLLocationCoordinate2D) -> CGPoint doesn't work correctly

### ISSUE THREAD

**Issue by Ogerets** [mapbox/mapbox-maps-ios#788] opened 2021-10-25 15:12 UTC
## Environment

- Xcode version: 12.5.1
- iOS version: 14.2
- Devices affected: tested on iPhone 6s, iPhone X
- Maps SDK Version: v10.0.1

## Observed behavior and steps to reproduce

When there is a non zero camera pitch, `MapboxMap.point(for: CLLocationCoordinate2D) -> CGPoint` returns totally incorrect CGPoint. When pitch is zero, it's working correctly.
Also zoom level seems to have some influence on this bug. As well as location of camera relative to coordinates.

 [Here](https://github.com/Ogerets/mapbox-convert-issue/tree/v10) is a sample project representing an issue with 100% reproduce rate.
 These are results of converting the **same** camera with different pitch:
 <img width="887" alt="Screenshot 2021-10-25 at 18 06 42" src="https://user-images.githubusercontent.com/20406383/138721428-91b9b1b9-5e52-4fd3-8f10-f12cee82beef.png">

## Expected behavior

Correctly converted point on view from coordinates even with non zero pitch

## Notes

I can see this bug in app with Mapbox v6.4.0. [Here](https://github.com/mapbox/mapbox-gl-native-ios/issues/638) is the similar issue for that version. I think a lot of guys on v6 will appreciate this bug being fixed on older version too.

## Additional links and references

 [Here](https://github.com/Ogerets/mapbox-convert-issue) is a sample project representing an issue

**Comment by endanke** [comment] 2021-11-02 14:33
@Ogerets originally you mentioned that the issue was first noticed in `v10.0.1`. Do you also have a sample to reproduce it there? We can backport the fix if needed, but primarily we would need to verify the issue in the newer version.

**Comment by Ogerets** [comment] 2021-11-02 15:26
@endanke Yes, sure. [Here](https://github.com/Ogerets/mapbox-convert-issue/tree/v10) it is. Sorry, I put the link to main branch in the issue description instead of `v10` branch.

**Comment by endanke** [comment] 2021-11-03 12:11
@Ogerets we've investigated this a bit further, thank you for the examples! Your illustration is on point, it seems like this is pretty much the reason for the issue. Unfortunately it's not a new bug, but a design limitation and it wasn't properly communicated in the documentation of this API.

Currently it's not clear how much effort would it take to rework the implementation of this function. Could you please share some details about your use-case? Maybe we could think about some alternatives to help you out.

**Comment by Ogerets** [comment] 2021-11-03 14:56
@endanke Got it. Thank you for the response!
My use-case: I'm showing a few nearby objects outside the mapView as icons at the edge of mapView. 
Originally my flow was
1. I convert object coordinates into the view point. It gives me a line segment between center of mapView & this point
2. Then I calculate the intersection of this line segment and screen boundaries to put icon at

Now I am thinking of a workaround:
 1. Calculate the heading between object coordinates and camera center
 2. Project this angle to mapView.
 3. Find the intersection of a line with this angle and screen boundaries.

Please point, if there are any utilities in Mapbox SDK v6 I can use for calculations in this workaround. 
Thank you in advance 🙏

**Comment by endanke** [comment] 2021-11-04 08:56
Unfortunately I don't know about any APIs that would specifically help with this, but one way you could try to do it:
1. Retrieve the coordinates of the corners of the map view using `mapView.mapboxMap.coordinate(for: CGPoint)`
2. Create a rectangle using these points (these will use the perspective projected coordinates)
3. Create a line segment using your object's coordinates and the center of the camera
4. Do an intersection test using your segment and the rectangle
5. Convert back the point to the screen coordinate using `self.mapView.mapboxMap.point(for: CLLocationCoordinate2D)`

**Comment by Ogerets** [comment] 2021-11-05 14:17
I'll try this out. Thank you for the advice 🙏

**Comment by endanke** [comment] 2022-03-10 07:04
Closing the issue as we're not planning to change this API at the moment.

**Closed** 2022-03-10 07:03 UTC
Labels: bug :beetle:

**Comment by akirmse** [comment] 2022-03-10 15:48
If you're not going to fix the API, maybe remove it?  There's no sense
having a call that returns random incorrect results.  Or at least document
that it cannot be called if pitch != 0, and have it throw an exception in
that case.

**Comment by endanke** [comment] 2022-03-10 16:46
I agree a documentation change would be needed at least. What's guaranteed is that the API will return a correct value if the requested coordinate is visible on the screen.

**Comment by endanke** [comment] 2022-05-23 08:53
Here's a sample implementation of the idea above: https://github.com/mapbox/mapbox-maps-ios/issues/788#issuecomment-960565313

Note: This solution is not complete, I assume we would either need a specialized intersection test that works with latitude longitude pairs or to convert them first to cartesian coordinates. 

```
// Add an annotation view to illustrate the position
let annotationView = AnnotationView(frame: CGRect(x: 0, y: 0, width: 128, height: 64))
annotationView.title = "Test"
self.lastView = annotationView
try? self.mapView.viewAnnotations.add(annotationView, options: ViewAnnotationOptions(
    geometry: Point(CLLocationCoordinate2D(latitude: 0.0, longitude: 0.0)),
    width: 128,
    height: 64,
    allowOverlap: true,
    anchor: .bottom
))

mapView.mapboxMap.onEvery(.cameraChanged) { [weak self] _ in
    guard let self = self else { return }

    let target = CLLocationCoordinate2D(latitude: 48.858093, longitude: 2.294694) // Paris
    let screenCenter = self.mapView.mapboxMap.coordinate(for: CGPoint(x: self.mapView.bounds.size.width / 2.0, y: self.mapView.bounds.size.height / 2.0))
                
    let southwest = self.mapView.mapboxMap.coordinate(for: CGPoint(x: self.mapView.bounds.size.width, y: self.mapView.bounds.size.height))
    let northeast = self.mapView.mapboxMap.coordinate(for: CGPoint(x: 0.0, y: 0.0))
    let northwest = self.mapView.mapboxMap.coordinate(for: CGPoint(x: self.mapView.bounds.size.width, y: 0.0))
    let southeast = self.mapView.mapboxMap.coordinate(for: CGPoint(x: 0.0, y: self.mapView.bounds.size.height))
    
    let point: CLLocationCoordinate2D = {
        if let westIntersection = self.intersection(start1: target.toPoint(), end1: screenCenter.toPoint(),
                                                    start2: northeast.toPoint(), end2: southeast.toPoint()) {
            return westIntersection
        }
        if let eastIntersection = self.intersection(start1: target.toPoint(), end1: screenCenter.toPoint(),
                                                    start2: northwest.toPoint(), end2: southwest.toPoint()) {
            return eastIntersection
        }
        if let northIntersection = self.intersection(start1: target.toPoint(), end1: screenCenter.toPoint(),
                                                        start2: northwest.toPoint(),   end2: northeast.toPoint()) {
            return northIntersection
        }
        if let southIntersection = self.intersection(start1: target.toPoint(), end1: screenCenter.toPoint(),
                                                        start2: southwest.toPoint(),  end2: southeast.toPoint()) {
            return southIntersection
        }
        // No intersection: target point is inside the bounds of the map view
        return target
    }()
    
    try? self.mapView.viewAnnotations.update(annotationView, options: ViewAnnotationOptions(geometry: Point(point)))
}
```

A slightly modified intersection test:

```
// Source: https://www.hackingwithswift.com/example-code/core-graphics/how-to-calculate-the-point-where-two-lines-intersect
func intersection(start1: CGPoint, end1: CGPoint, start2: CGPoint, end2: CGPoint) -> CLLocationCoordinate2D? {
    // calculate the differences between the start and end X/Y positions for each of our points
    let delta1x = end1.x - start1.x
    let delta1y = end1.y - start1.y
    let delta2x = end2.x - start2.x
    let delta2y = end2.y - start2.y

    // create a 2D matrix from our vectors and calculate the determinant
    let determinant = delta1x * delta2y - delta2x * delta1y

    if abs(determinant) < 0.0001 {
        // if the determinant is effectively zero then the lines are parallel/colinear
        return nil
    }

    // if the coefficients both lie between 0 and 1 then we have an intersection
    let ab = ((start1.y - start2.y) * delta2x - (start1.x - start2.x) * delta2y) / determinant

    if ab > 0 && ab < 1 {
        let cd = ((start1.y - start2.y) * delta1x - (start1.x - start2.x) * delta1y) / determinant

        if cd > 0 && cd < 1 {
            // lines cross – figure out exactly where and return it
            let intersectX = start1.x + ab * delta1x
            let intersectY = start1.y + ab * delta1y
            return CLLocationCoordinate2DMake(intersectX, intersectY)
        }
    }

    // lines don't cross
    return nil
}
```

```
extension CLLocationCoordinate2D {
    
    func toPoint() -> CGPoint {
        return CGPoint(x: latitude, y: longitude)
    }
    
}
```

**Comment by teddichiiwa** [comment] 2022-10-26 04:37
Change `abs(determinant)` from 0.0001 to 0.00000001 will snap to the correct offset in max zoom level 👍
