### ISSUE TITLE
High CPU usage while MapView is idle

### ISSUE THREAD

**Issue by RodrigoSAlves** [mapbox/mapbox-maps-ios#1558] opened 2022-09-06 23:28 UTC
## Environment

- Xcode version: 13.4.1
- iOS version: 15.6
- Devices affected: iPhone XR
- Maps SDK Version: 1.7.0 (my app) / 1.8.0-rc.1 (Examples app)

## Observed behavior and steps to reproduce

Unexpected continuous high CPU usage, even while map is idle.

## Expected behavior

Expected CPU usage while the user is not interacting with a MapView / Map is not being updated to be at least close to 0%.

## Notes / preliminary analysis

After using the profiler, it seems that the "update" function of ForwardingDisplayLinkTarget class is being called in a loop, which subsequently leads to the "updateFromDisplayLink" from MapView class to be called several times per second and re-render the map?

In my app, which uses a very complex custom style, the CPU utilisation continuously hovers 50%. 
I managed to reproduce this behaviour in the Examples App, running the "Customize the location puck" (Custom2DPuckExample.swift) example. Although the continuous CPU utilisation is lower in the Examples app (hovers around 11%), the same behaviour can be seen in the profiler.
I'm not 100% sure, but at least in my app, the problem seems occur when I have the map centred on the user's location. If slew the map to another area, it seems to fade away.

## Additional links and references
Here's a few screenshots from the Profile, while running the Examples app.

<img width="1920" alt="Screenshot 2022-09-07 at 00 29 27" src="https://user-images.githubusercontent.com/19390670/188757654-3b860925-e30c-4ef9-b3b0-2e35b2f502c8.png">
<img width="1434" alt="Screenshot 2022-09-07 at 00 29 51" src="https://user-images.githubusercontent.com/19390670/188757653-ad20d5b4-1ac5-498d-b146-9dbc09a51629.png">

**Comment by ZiZasaurus** [comment] 2022-09-08 21:11
@RodrigoSAlves, closing this as a duplicate of https://github.com/mapbox/mapbox-maps-ios/issues/1537

**Closed by ZiZasaurus** 2022-09-08 21:11 UTC
Labels: bug :beetle:

**Comment by evil159** [comment] 2022-12-08 13:38
@RodrigoSAlves thank you for the detailed report, we have identified the cause of excessive CPU usage and fixed in in https://github.com/mapbox/mapbox-maps-ios/pull/1789
