### ISSUE TITLE
Jerky transitions when zooming into tiles

### ISSUE THREAD

**Issue by ibmeister** [mapbox/mapbox-maps-ios#1628] opened 2022-10-06 22:17 UTC
This would be useful towards drastically improving the UX of certain transitions

Seems like this feature was already rolled out for mapbox js https://github.com/mapbox/mapbox-gl-js/issues/2470

**Comment by ZiZasaurus** [comment] 2022-10-07 22:28
@ibmeister we do support pre-fetching. Please take a look at our documentation [here](https://docs.mapbox.com/ios/maps/api/10.8.1/Classes/MapboxMap.html#/Prefetching). Specific information on various layers/sources that support prefetching can be found below: 

- [vector sources](https://docs.mapbox.com/ios/maps/api/10.8.1/Structs/VectorSource.html#/s:10MapboxMaps12VectorSourceV17prefetchZoomDeltaSdSgvp)
- [raster sources](https://docs.mapbox.com/ios/maps/api/10.8.1/Structs/RasterSource.html#/s:10MapboxMaps12RasterSourceV17prefetchZoomDeltaSdSgvp)
- [rasterDEMsources](https://docs.mapbox.com/ios/maps/api/10.8.1/Structs/RasterDemSource.html#/s:10MapboxMaps15RasterDemSourceV17prefetchZoomDeltaSdSgvp)
- [image sources](https://docs.mapbox.com/ios/maps/api/10.8.1/Structs/ImageSource.html#/s:10MapboxMaps11ImageSourceV17prefetchZoomDeltaSdSgvp)
- [geoJSON sources](https://docs.mapbox.com/ios/maps/api/10.8.1/Structs/GeoJSONSource.html#/s:10MapboxMaps13GeoJSONSourceV17prefetchZoomDeltaSdSgvp)

**Comment by ibmeister** [comment] 2022-10-11 14:58
> @ibmeister we do support pre-fetching. Please take a look at our documentation [here](https://docs.mapbox.com/ios/maps/api/10.8.1/Classes/MapboxMap.html#/Prefetching). Specific information on various layers/sources that support prefetching can be found below:
> 
> * [vector sources](https://docs.mapbox.com/ios/maps/api/10.8.1/Structs/VectorSource.html#/s:10MapboxMaps12VectorSourceV17prefetchZoomDeltaSdSgvp)
> * [raster sources](https://docs.mapbox.com/ios/maps/api/10.8.1/Structs/RasterSource.html#/s:10MapboxMaps12RasterSourceV17prefetchZoomDeltaSdSgvp)
> * [rasterDEMsources](https://docs.mapbox.com/ios/maps/api/10.8.1/Structs/RasterDemSource.html#/s:10MapboxMaps15RasterDemSourceV17prefetchZoomDeltaSdSgvp)
> * [image sources](https://docs.mapbox.com/ios/maps/api/10.8.1/Structs/ImageSource.html#/s:10MapboxMaps11ImageSourceV17prefetchZoomDeltaSdSgvp)
> * [geoJSON sources](https://docs.mapbox.com/ios/maps/api/10.8.1/Structs/GeoJSONSource.html#/s:10MapboxMaps13GeoJSONSourceV17prefetchZoomDeltaSdSgvp)

Thank you @ZiZasaurus. I tried this and it unfortunately doesn't seem to be giving the desired results. The problem still remains. 

On our app launch, we do a zoom in from the globe view to the user's location, and every time this is done for the first time that zoom in is jerky even though we only trigger the zoom in on .mapLoaded (presumably because it's still loading and caching tiles to the device, but could be for other reasons too) . However, on subsequent launches the zoom in is smooth (presumably because all the caching has already been done).

Do you have any hints on what might be happening here and how we can resolve this? We want to make a good impression with our first-time users and my assumption was that preloading the tiles before zoom in would solve the jerky first-time zoom, but I may be wrong.

**Comment by ZiZasaurus** [comment] 2022-11-08 14:31
@ibmeister could you please provide a screen recording of the jerky behavior? Additionally, what version are you experiencing this behavior on?

**Comment by ibmeister** [comment] 2022-11-18 14:03
Hi @ZiZasaurus,

I created a more specific/reproducible issue for this. Please take a look. Should happen if you run the sample code on first install https://github.com/mapbox/mapbox-maps-ios/issues/1679

**Comment by ZiZasaurus** [comment] 2022-11-19 13:47
@ibmeister, closing this ticket as a duplicate of #1679 to track responses in one ticket.

**Closed by ZiZasaurus** 2022-11-19 13:47 UTC
