### ISSUE TITLE
Polyline drawn does not connect all waypoints

### ISSUE THREAD

**Issue by Subhashini2610** [mapbox/mapbox-maps-ios#1178] opened 2022-03-08 15:57 UTC
## Environment

- Xcode version: 13.2.1
- iOS version: 15.3.1
- Devices affected: iPhone 12, iPhone 7
- Maps SDK Version: Mapbox Maps 10.1.2, Directions 2.3.0

## Observed behavior and steps to reproduce

I am having trouble drawing a polyline consisting of waypoints received from my custom server. The polyline received from Directions.calculateRoutes only joins the first two waypoints. I have a total of 27 points that I feed into the Directions.calculateRoutes API. Below is my full code:
```
//custom server to fetch waypoints
        NetworkManager.shared.getRoute(startLon: 9.1407, startLat: 48.6980, endLon:9.0074, endLat: 48.6845) { [unowned self] routeResponse, error in
            if (error != nil) {
                debugPrint("Error in fetching route: \(String(describing: error?.description))")
            } else {
                debugPrint("Route received")
                if let route = routeResponse?.route {
                    
                    var lineCoordinates = []
                    var locationCoords = [CLLocationCoordinate2D]()
                    
                    for location in route {
                        let waypoint = Waypoint(coordinate: CLLocationCoordinate2DMake(location.lat, location.lon))
                        locationCoords.append(CLLocationCoordinate2DMake(location.lat, location.lon))
                        waypoint.separatesLegs = true
                        lineCoordinates.append(waypoint)
                    }
                    
                    let options = MatchOptions(waypoints: lineCoordinates, profileIdentifier: .automobile)//waypoints stored in lineCoordinates array 
                    options.includesSteps = true
                    
                    var routeDetailedCoordinates = [CLLocationCoordinate2D]()

                    
                    _ = Directions.shared.calculateRoutes(matching: options, completionHandler: { [unowned self] session, result in
                        switch result {
                        case .failure(let error):
                            print(error.localizedDescription)
                        case .success(let response):
                            guard let route = response.routes?.first else {
                                return
                            }
                            
                            for leg in route.legs {
                                for step in leg.steps {
                                    if let coordinates = step.shape?.coordinates {
                                        for point in coordinates {
                                            routeDetailedCoordinates.append(CLLocationCoordinate2DMake(point.latitude, point.longitude))
                                            
                                        }
                                    }
                                    
                                }
                            }
                            
                            
                            //plot server points on map
                            let pointAnnotationManager = mapView.annotations.makePointAnnotationManager(id: UUID().uuidString, layerPosition: nil)
                                     
                            var waypointsArray = [PointAnnotation]()

                            for coord in lineCoordinates {
                                var customPointAnnotation = PointAnnotation(coordinate: coord.coordinate)
                                customPointAnnotation.image = .init(image: UIImage(named: "map-marker")!, name: "map-marker")

                                waypointsArray.append(customPointAnnotation)
                            }
                             
                            pointAnnotationManager.annotations = waypointsArray
                            
                            
                            //draw polyline route on map
                            var lineAnnotation = PolylineAnnotation(lineCoordinates: routeDetailedCoordinates)
                            
                            // Customize the style of the line annotation
                            lineAnnotation.lineColor = StyleColor(red: 9, green: 132, blue: 255, alpha: 1.0)
                            lineAnnotation.lineOpacity = 0.8
                            lineAnnotation.lineWidth = 4.0
                            
                            let lineAnnnotationManager = mapView.annotations.makePolylineAnnotationManager(id: "lineAnnotations", layerPosition: nil)
                            lineAnnnotationManager.annotations = [lineAnnotation]
                            
                            //set the bounding box
                            let insets = UIEdgeInsets(top: 24, left: 24, bottom: 24, right: 24)

                            let camera = mapView.mapboxMap.camera(for: locationCoords, padding: insets, bearing: nil, pitch: nil)
                            self.mapView.mapboxMap.setCamera(to: camera)
                            
                        }
                    })
                                            

                    }
                }
            }
```
**Note: The same code was working for the same waypoints until a week back, but now I have stumbled upon this problem.**
This is the polyline being drawn currently(note the waypoints are annotated):
![IMG_8417](https://user-images.githubusercontent.com/54573581/156992752-42ae8021-f85e-4788-8557-3df0f53ea4a0.PNG)

## Additional links and references

I have created an issue for the same on the Directions repo as well: https://github.com/mapbox/mapbox-directions-swift/issues/661#issue-1161050019

**Comment by ZiZasaurus** [comment] 2022-03-08 21:26
Closing this as a duplicate of https://github.com/mapbox/mapbox-directions-swift/issues/661

**Closed by ZiZasaurus** 2022-03-08 21:26 UTC
Labels: bug :beetle:
