### ISSUE TITLE
Adding off-screen Annotation UIView will cause it to appear on the top left of the screen

### ISSUE THREAD

**Issue by jimmy0804** [mapbox/mapbox-maps-ios#1580] opened 2022-09-14 16:02 UTC
## Environment

- Xcode version: 13.4
- iOS version: 14.4, 15.5 or 16.0. Basically I am confident to say it affects all iOS version.
- Devices affected: iPhone X, iPhone 11
- Maps SDK Version: 10.7 and 10.8.1 (not seen in version 10.5.1)

## Observed behavior and steps to reproduce

Adding a UIView annotation that has off-screen coordinate assigned will result the newly added to appear on map.

<img width="431" alt="Screen Shot 2022-09-14 at 17 00 09" src="https://user-images.githubusercontent.com/8681991/190204610-62a5e81b-3b82-4688-a6b7-2816889d2f06.png">

## Expected behavior

The newly added annotation should not appear on the map if its coordinate is not part of the current camera view port.

## Notes / preliminary analysis

On version 10.5.1, when adding a custom UIView annotation using ViewAnnotationManager with a coordinate that is currently off-screen, using [onViewAnnotationPositionsUpdate(forPositions:)](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Annotations/ViewAnnotationManager.swift#L369) will get called which trigger [placeAnnotations(positions:)](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Annotations/ViewAnnotationManager.swift#L288) to hide the newly added off-screen view annotation.

However, after upgraded to SDK version 10.7 or even the latest version 10.8.1, [onViewAnnotationPositionsUpdate(forPositions:)](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Annotations/ViewAnnotationManager.swift#L369) does not get called if I add a new view annotation that is currently off-screen. Since [add(view:id :options:)](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Annotations/ViewAnnotationManager.swift#L132) will add the view directly to containerView, the newly added UIView will get rendered on the screen with frame's origin being (0,0).

IMO, PlaceAnnotations(positions:) should get called when a new view annotation is being added or there should be some logic change inside [add(view:id :options:)](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Annotations/ViewAnnotationManager.swift#L132) function.

To by-pass this issue, I am currently setting the UIView.isHidden to false before adding the view to ViewAnnotationManager. This will trigger a warning in Mapbox but I don't have any other way around it.

**Comment by ZiZasaurus** [comment] 2022-09-15 05:25
@jimmy0804 thank you for reporting this behavior. The team will look into the root cause and report back soon.

**Comment by tungvustarglobal** [comment] 2022-09-20 08:02
I've faced the same issue on iOS 16

**Comment by Surferdude667** [comment] 2022-10-03 14:22
I face the same problem.

**Comment by evil159** [comment] 2022-10-06 14:44
Thank you @jimmy0804 for a detailed report! This issue is addressed in https://github.com/mapbox/mapbox-maps-ios/pull/1627(scheduled to be released in v10.10.0).

**Closed by evil159** 2022-10-06 14:44 UTC
Labels: bug :beetle:

**Comment by ghraibeh** [comment] 2022-11-10 11:18
I'm facing the same issue. We have downgraded to 10.6.0 and everything is working fine now

**Comment by evil159** [comment] 2022-11-10 11:48
@ghraibeh This issue is fixed in [v10.10.0-beta.1](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.10.0-beta.1).
