### ISSUE TITLE
Is there a way to programmatically set the camera position with coordinate bounds, after Map is created in SwiftUI

### ISSUE THREAD

**Issue by kaspesi** [mapbox/mapbox-maps-ios#2016] opened 2023-09-07 02:59 UTC
## New Feature?

Previously in Swift (Before MapBox 11 Beta) we were able to do something like this:

```
let bounds = CoordinateBounds(southwest: southWest,
                                      northeast: northEast)
let camera = mapView.mapboxMap.camera(for: bounds, padding: .zero, bearing: 0, pitch: 0)
```

In MapBox SwiftUI we create map with:
```
Map.init(viewport: Binding<Viewport>, @MapContentBuilder content: @escaping () -> MapContent)
   .cameraBounds(CameraBoundsOptions(bounds:...)
```

Using .cameraBounds does not work since it limits the Map to these bounds.

Via the view port binding we can update the cameraOptions:

init(cameraState: CameraState, anchor: CGPoint?) 
init(center: CLLocationCoordinate2D?, padding: UIEdgeInsets?, anchor: CGPoint?, zoom: CGFloat?, bearing: CLLocationDirection?, pitch: CGFloat?)
init(from: Decoder) throws

But as far as I can tell, all we can control is where the center of the map is, and then zoom out.

## Why
<- 1-2 sentence description of why you're requesting this feature. What problem does it solve? Why is it valuable? ->

When adding ViewAnnotations to the map, it makes sense to have a feature that zoom the map to fit all the annotations on the map.  This is easy to do when you can take the min/max of the set of Coordinates to find the correct southWest/northEast bounding box.  

Something like this is unnecessarily complicated when you have to set it by finding the center and then the correct zoom.

**Comment by kaspesi** [comment] 2023-09-07 03:20
Using `.cameraBounds` is not a work around here to be clear.  It also makes it so we are stuck within those bounds it does not just set the cameras view to those bounds.

**Comment by persidskiy** [comment] 2023-09-11 11:33
Hi @kaspesi , thank you for the feedback!

You can use overview viewport to set camera that overviews the annotations. https://docs.mapbox.com/ios/maps/api/11.0.0-beta.2-docc/documentation/mapboxmaps/swiftui-user-guide/#Using-Viewport-to-manage-camera.

In your case, the code might look like this:
```
struct MyView: View {
   @State var viewport: Viewport = .styleDefault
   var body: some View {
      Map(viewport: $viewport)
         .onAppear {
            let points = MultiPoint([
               CLLocationCoordinate2D(...),
               CLLocationCoordinate2D(...),
            ])
            viewport = .overview(geometry: points)
         }
   }
}
```

Also, usually annotations consume some space, so you might want to inset the resulting viewport a little bit:
```
viewport = .overview(geometry: points).inset(edges: .all, length: 20))
```

I'm closing this issue, please feel free to reopen it if my answer didn't help.

**Closed by persidskiy** 2023-09-11 11:33 UTC
Labels: SwiftUI

**Comment by jhoanarango** [comment] 2024-02-07 20:59
@persidskiy, 

Thank you for this. However, there might be a bug here unless I am not doing it right. 

I am using the overview to center the camera between several coordinates as shown on the screenshot below. 

<img width="351" alt="Screenshot 2024-02-07 at 3 34 46 PM" src="https://github.com/mapbox/mapbox-maps-ios/assets/14069813/26e1f068-69e4-4d5f-a0b8-97e480bcdf61">
 
 ### 


The user can see other routes they have done by tapping on different months via a button. Thus, a new overview should center the map to see the new routes. So far so good. However, for some odd reason the "padding" is not adjusting with the new change. 

Here is the code:

**WHEN THE USER FIRST OPENS THE MAP WE USE .onAppear**

```swift
            .onAppear {
                let airports = summary?.routes.flatMap { $0.airports }
                
                if let points = airports.flatMap({ $0.map { $0.coordinate } }) {
                    let multiPoints = MultiPoint(points)
                    viewport = .overview(geometry: multiPoints, geometryPadding: .init(top: 10, leading: 10, bottom: 10, trailing: 10), maxZoom: 3, offset: .zero)
                }
            }

```

**THIS IS THE RESULT BELOW** which looks as intended  ✅


<img width="346" alt="Screenshot 2024-02-07 at 3 46 06 PM" src="https://github.com/mapbox/mapbox-maps-ios/assets/14069813/de23746e-05ac-4f60-824c-e716d6460300">

 ###

When the user taps on a new month, it should recenter with the new overview, but it is not adjusting its padding. I have even adjusted the padding to a higher number and see if that works but nothing.  Here is the code and the result.

```swift

            .onChange(of: summary?.routes) { oldValue, newValue in
                withViewportAnimation {
                    let airports = newValue?.flatMap { $0.airports }
                    
                    if let points = airports.flatMap({ $0.map { $0.coordinate } }) {
                        let multiPoints = MultiPoint(points)
                        viewport = .overview(geometry: multiPoints, geometryPadding: .init(top: 120, leading: 120, bottom: 120, trailing: 120), maxZoom: 3, offset: .zero)
                    }
                }
            }

```

**HERE IS THE RESULT**

<img width="349" alt="Screenshot 2024-02-07 at 3 53 11 PM" src="https://github.com/mapbox/mapbox-maps-ios/assets/14069813/200fefa0-3720-497c-9c53-7a75c96d8b03">

###

As you can see, it does not adjust the padding. The cities are way too close to the edges, no matter the value I add to the padding. 

Please let me know if I am doing something wrong or if this is a bug.

**Comment by jhoanarango** [comment] 2024-02-07 21:30
I think it is a bug.. by the way, I am using the latest update of MapBox 11.1.0

Here are my findings..

While using the mapStyle = .standard the map does not seem to respect the values for the padding as shown on my previous reply. 

However, when I change into mapStyle = .satellite, the map does respect the paddings and works as expected. When I change back into .standard, then the app goes back to the broken behavior.

```swift

            .mapStyle(colorScheme == .light ? .standard : .satellite) <--- NEW CODE
            .frame(height: 285)
            .onAppear {
                let airports = summary?.routes.flatMap { $0.airports }
                
                if let points = airports.flatMap({ $0.map { $0.coordinate } }) {
                    let multiPoints = MultiPoint(points)
                    viewport = .overview(geometry: multiPoints, geometryPadding: .init(top: 10 , leading: 10, bottom: 10, trailing: 10), maxZoom: 3, offset: .zero)
                }
            }
            .onChange(of: summary?.routes) { oldValue, newValue in
                withViewportAnimation {
                    let airports = newValue?.flatMap { $0.airports }
                    
                    if let points = airports.flatMap({ $0.map { $0.coordinate } }) {
                        let multiPoints = MultiPoint(points)
                        viewport = .overview(geometry: multiPoints, geometryPadding: .init(top: 10, leading: 120, bottom: 10, trailing: 120), maxZoom: 3, offset: .zero)
                    }
                }
            }
```

Should I open a new bug report?
