### ISSUE TITLE
[10.5.0-beta.1] Users cannot zoom when 3D tiles are used with exaggeration set to 0

### ISSUE THREAD

**Issue by devioustree** [mapbox/mapbox-maps-ios#1279] opened 2022-04-19 00:12 UTC
## Environment

- Xcode version: 13.3.1
- iOS version: 15.5
- Devices affected: All
- Maps SDK Version: `10.5.0-beta.1`

## Observed behavior and steps to reproduce

In the latest beta, users are unable to zoom a map with 3d terrain enabled if the exaggeration is set to 0. Neither double-tap to zoom, or pinch zooming works.

I've attached a `diff` to apply to the repo. Run the **Show 3D Terrain** example and try to zoom in. This appears to be a new bug as I could not reproduce in 10.4.2.

## Additional links and references

```diff
diff --git a/Apps/Examples/Examples/All Examples/TerrainExample.swift b/Apps/Examples/Examples/All Examples/TerrainExample.swift
index 032aebcc..7d6acebc 100644
--- a/Apps/Examples/Examples/All Examples/TerrainExample.swift	
+++ b/Apps/Examples/Examples/All Examples/TerrainExample.swift	
@@ -13,7 +13,7 @@ public class TerrainExample: UIViewController, ExampleProtocol {
         let camera = CameraOptions(center: centerCoordinate,
                                    zoom: 13.1,
                                    bearing: 80,
-                                   pitch: 85)
+                                   pitch: 0)
         let options = MapInitOptions(
             cameraOptions: camera,
             styleURI: StyleURI(rawValue: "mapbox://styles/mapbox-map-design/ckhqrf2tz0dt119ny6azh975y")!)
@@ -38,7 +38,7 @@ public class TerrainExample: UIViewController, ExampleProtocol {
         try! mapView.mapboxMap.style.addSource(demSource, id: "mapbox-dem")
 
         var terrain = Terrain(sourceId: "mapbox-dem")
-        terrain.exaggeration = .constant(1.5)
+        terrain.exaggeration = .constant(0)
 
         try! mapView.mapboxMap.style.setTerrain(terrain)
 ```

https://user-images.githubusercontent.com/38645/163896049-d78f8cba-183d-4511-bfed-f8cf2cced553.mp4

**Comment by astojilj** [comment] 2022-04-26 17:33
Fix for the issue is under work. Meanwhile, have you reconsidered [removing terrain](https://docs.mapbox.com/ios/maps/api/10.4.3/Classes/Style.html#/s:10MapboxMaps5StyleC13removeTerrainyyF) for the case when exaggeration would be 0?

If your style includes hillshade layer that is using the same source as the terrain is using (`id: "mapbox-dem"`), then it is advisable not to remove terrain. This is because hillshade layer and terrain share the same raster-dem tiles and terrain removal would result with hillshade layer using higher amount of tiles and potential performance regression.

If your style is not including a hillshade layer that shares the raster-dem source with terrain, terrain removal for exaggeration 0 might make sense, if application is not expected to change the exaggeration back `often` (subjective). Setting exaggeration to 0 and removing terrain are not rendering the same way (terrain with exaggeration 0 would still drape fill, line, raster layers over flat terrain). Terrain with exaggeration 0 would still issue network requests for raster dem tiles, preparing for the case when exaggeration change...

**Comment by ZiZasaurus** [comment] 2022-07-30 02:25
@devioustree the PR responsible for this has been merged. I will close this ticket, but please feel free to reopen if the issue resurfaces.

**Closed by ZiZasaurus** 2022-07-30 02:25 UTC
Labels: bug :beetle:
