### ISSUE TITLE
Expose and modify the rotation threshold

### ISSUE THREAD

**Issue by MatteoAlberghini** [mapbox/mapbox-maps-ios#755] opened 2021-10-13 10:43 UTC
## New Feature
At the moment we have no way (if I'm not mistaken) to decrease the rotation threshold on iOS. When a user is zooming in, sometimes the rotation threshold is too low and the user ends up rotating the map while zooming.
On android SDK, we have a setDisableRotateWhenScaling ([reference](https://docs.mapbox.com/android/maps/api/9.6.1/?com/mapbox/mapboxsdk/maps/UiSettings.html)) where we can at least remove the rotation when scaling, but I didn't see anything like this for iOS (Although having a threshold would be better).

## Why
Is something that's been requested and added in other Mapbox SDKs, it's also useful for developers to be able to target elderly users (it's hard for them to zoom in without rotating the map) or simply customize the Mapbox gestures even more.

**Comment by dandyweng** [comment] 2021-11-06 09:06
Hi @ZiZasaurus, I would love to see this gets implemented. I don’t think the current version of v10 SDK even has a rotation threshold, as the bearing changes freely with a pinch gesture, which is super annoying when a user just wants to zoom in or out.

I even considered downgrading the SDK to previous versions because of this issue until I found out this (undocumented?) way to disable rotation here. Even if the threshold is not exposed to developers please consider setting the default value to match the behavior of previous SDKs.

**Comment by ts95** [comment] 2022-01-05 08:38
> I don’t think the current version of v10 SDK even has a rotation threshold, as the bearing changes freely with a pinch gesture, which is super annoying when a user just wants to zoom in or out.

I also immediately noticed this after updating to v10 and it's not optimal. I'll disable pinch rotation in the meantime.

**Comment by georgbachmann** [comment] 2022-02-01 14:24
Just got told that my #1076 is a duplicate of that one here! Sorry... did see that one!

A huge +1 from me. I also noticed it right away and it just does not feel as good as the previous versions.
Also, the default Apple-Maps app does something similar. Snapping back to 0° when close enough and also having a little threshold.
I'd LOVE to see a manually configurable threshold, but having at least some would be a huge benefit already!

**Comment by reubn** [comment] 2022-03-09 20:12
Blocking for me

**Comment by georgbachmann** [comment] 2022-04-01 08:14
@ZiZasaurus is there any update on that feature-request?

**Comment by georgbachmann** [comment] 2022-04-15 07:23
@ZiZasaurus is there any update on that issue? This is a blocking issue for us, as the map in our app has quite an important role and not being able to "properly zoom" is quite a dealbreaker. Currently I can't zoom in or out without at least slightly rotating the map. This is not that nice. Would be awesome if you would add that threshold!

**Comment by nenadcowboy** [comment] 2022-04-26 13:07
Any update?

**Comment by ZiZasaurus** [comment] 2022-05-03 15:51
Hi all, thank you for following up. This enhancement has been added to our short-term roadmap.

**Comment by evil159** [comment] 2022-07-06 10:17
This is addressed in https://github.com/mapbox/mapbox-maps-ios/pull/1429

**Closed** 2023-02-08 17:39 UTC
Labels: feature :green_apple:
