### ISSUE TITLE
MapboxMap method func camera(for:padding:bearing:pitch:) -> CameraOptions returns wrong value

### ISSUE THREAD

**Issue by lmelnykmylivn** [mapbox/mapbox-maps-ios#687] opened 2021-09-17 11:41 UTC
## Environment

- Xcode version: 12.5.1 (12E507)
- iOS version: 14.7
- Devices affected: iPhoneX, iPhone 8 (I believe all versions)
- Maps SDK Version: 10.0.0-rc.7/10.0.0-rc.8

## Observed behavior and steps to reproduce

Here is code snippep:
```swift
    func setRegion(_ region: MapRegion,
                   edgePadding: UIEdgeInsets = .zero,
                   animationDuration: TimeInterval? = nil,
                   completion: (() -> Void)? = nil) {
        let bounds = CoordinateBounds(southwest: region.southWest, northeast: region.northEast)
        let cameraOption = mapboxMap.camera(for: bounds, padding: edgePadding, bearing: nil, pitch: nil)
        if let duration = animationDuration, duration > 0 {
            camera.ease(to: cameraOption, duration: duration, curve: .easeInOut) { _ in
                completion?()
            }
        } else {
            mapboxMap.setCamera(to: cameraOption)
            completion?()
        }
    }
```

Input parameters are:
```
(lldb) po edgePadding
▿ UIEdgeInsets
  - top : 122.0
  - left : 32.0
  - bottom : 102.0
  - right : 32.0
 
(lldb) po region.southWest
▿ CLLocationCoordinate2D
  - latitude : 48.06263993370894
  - longitude : 11.283150295247417

(lldb) po region.northEast
▿ CLLocationCoordinate2D
  - latitude : 48.28977617341681
  - longitude : 11.623576615028078

(lldb) po bounds.southwest
▿ CLLocationCoordinate2D
  - latitude : 48.06263993370894
  - longitude : 11.283150295247417

(lldb) po bounds.northeast
▿ CLLocationCoordinate2D
  - latitude : 48.28977617341681
  - longitude : 11.623576615028078
```
Map view bounds are:
```
 (lldb) po self.bounds
▿ (0.0, 0.0, 375.0, 673.0)
  ▿ origin : (0.0, 0.0)
    - x : 0.0
    - y : 0.0
  ▿ size : (375.0, 673.0)
    - width : 375.0
    - height : 673.0
 ```

But camera options center is definitely wrong:
```
(lldb) po cameraOption
▿ CameraOptions
  ▿ center : Optional<CLLocationCoordinate2D>
    ▿ some : CLLocationCoordinate2D
      - latitude : 14.663274114713758
      - longitude : 11.45336345513823
  ▿ padding : Optional<UIEdgeInsets>
    ▿ some : UIEdgeInsets
      - top : 122.0
      - left : 32.0
      - bottom : 102.0
      - right : 32.0
  - anchor : nil
  ▿ zoom : Optional<CGFloat>
    - some : 9.32720936512057
  - bearing : nil
  - pitch : nil
```

## Expected behavior

The camera options center should present the valid center of coordinate bounds

Best regards,
Leonid at Mylivn

**Comment by macdrevx** [comment] 2021-09-17 12:54
@lmelnykmylivn could you share what the value of `mapboxMap.cameraState` is before you invoke `camera(for:...)`?

**Comment by lmelnykmylivn** [comment] 2021-09-17 16:07
Hi @macdrevx,

Probably it will be useful to mention that I'm changing camera two times in a row, the first time without animation using method `mapboxMap.setCamera(to: cameraOption)` and the second one with animation using `camera.ease(to: cameraOption, duration: duration, curve: .easeInOut)...`

I've added some loggings:
```swift
    func setRegion(_ region: MapRegion,
                   edgePadding: UIEdgeInsets = .zero,
                   animationDuration: TimeInterval? = nil,
                   completion: (() -> Void)? = nil) {
        let currentCamera = cameraState
        print("Current camera options:")
        print("  center: \(currentCamera.center.latitude),\(currentCamera.center.longitude)")
        print("  padding: \(currentCamera.padding)")
        print("  zoom: \(currentCamera.zoom)")
        print("  bearing: \(currentCamera.bearing)")
        print("  pitch: \(currentCamera.pitch)")
        
        let bounds = CoordinateBounds(southwest: region.southWest, northeast: region.northEast)
        print("Input params:")
        print("  bounds: sw: \(bounds.southwest.latitude),\(bounds.southwest.longitude); ne: \(bounds.northeast.latitude),\(bounds.northeast.longitude);")
        print("  padding: \(edgePadding)")
        
        let cameraOption = mapboxMap.camera(for: bounds, padding: edgePadding, bearing: nil, pitch: nil)
        print("Camera options to set:")
        if let center = cameraOption.center {
            print("  center: \(center.latitude),\(center.longitude)")
        }
        if let padding = cameraOption.padding {
            print("  padding: \(padding)")
        }
        if let anchor = cameraOption.anchor {
            print("  anchor: \(anchor)")
        }
        if let zoom = cameraOption.zoom {
            print("  zoom: \(zoom)")
        }
        if let bearing = cameraOption.bearing {
            print("  bearing: \(bearing)")
        }
        if let pitch = cameraOption.pitch {
            print("  pitch: \(pitch)")
        }
        
        if let duration = animationDuration, duration > 0 {
            camera.ease(to: cameraOption, duration: duration, curve: .easeInOut) { _ in
                completion?()
            }
        } else {
            mapboxMap.setCamera(to: cameraOption)
            completion?()
        }
    }
```

Here is the output
```
-= Without animation using  `mapboxMap.setCamera(to:)` =-

Current camera options:
  center: 21.16056060791016,-86.84750366210936
  padding: UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0)
  zoom: 13.0
  bearing: -0.0
  pitch: 0.0
Input params:
  bounds: sw: 48.1352744601127,11.531038215644607; ne: 48.22117543676765,11.543917784279692;
  padding: UIEdgeInsets(top: 122.0, left: 32.0, bottom: 102.0, right: 32.0)
Camera options to set:
  center: 21.93966080514575,11.537477999963585
  padding: UIEdgeInsets(top: 122.0, left: 32.0, bottom: 102.0, right: 32.0)
  zoom: 11.25896595877158

-= Animated using camera.ease(to:duration:,curve:completion:) =-

Current camera options:
  center: 21.939660805145714,11.537477999963585
  padding: UIEdgeInsets(top: 122.0, left: 32.0, bottom: 102.0, right: 32.0)
  zoom: 11.25896595877158
  bearing: -0.0
  pitch: 0.0
Input params:
  bounds: sw: 48.167487326358305,11.535868053882764; ne: 48.188962570522044,11.539087946041535;
  padding: UIEdgeInsets(top: 122.0, left: 32.0, bottom: 102.0, right: 32.0)
Camera options to set:
  center: 24.517673039692895,11.537477999961538
  padding: UIEdgeInsets(top: 122.0, left: 32.0, bottom: 102.0, right: 32.0)
  zoom: 13.258966401874899
```

**Comment by SkylerSeamans** [comment] 2021-11-04 19:24
This also affects func camera(for:padding:bearing:pitch:).

Attached is a video as well as an exampled based on the MultiplePointAnnotation sample code. In my testing, the outcome of func camera(for:padding:bearing:pitch:) seems dependent on the zoom level of the camera at the time of the function call. Zoom levels greater than 9 seems to make the behavior apparent.

In my video, tapping the bar button item loads the annotations around portland. If I zoom greater than level 9, tapping the button results in weird results. If I am at a higher zoom level, the camera results are accurate. I tap the button 2x. The first tap loads a strange camera result. The 2nd tap loads the results correctly. The data set is static.

https://user-images.githubusercontent.com/3864580/140406271-4e95751e-23d5-45fb-95af-1a18aebc7962.mov

`import UIKit
import MapboxMaps
import CoreLocation
import MapKit

@objc(MultiplePointAnnotationsExample)
public class MultiplePointAnnotationsExample: UIViewController, ExampleProtocol {
    internal var mapView: MapView!
    var annotations: [PointAnnotation] {
        get {
            return pointAnnotationManager.annotations
        }
    }
    // Keep a reference to the point annotation manager as a property.
    // If the annotation manager is destroyed, the annotations will be removed from the map.
    internal lazy var pointAnnotationManager: PointAnnotationManager = {
        return mapView.annotations.makePointAnnotationManager()
    }()

    override public func viewDidLoad() {
        super.viewDidLoad()

        // Set the map's initial center coordinate and zoom level.
        let center = CLLocationCoordinate2D(latitude: 37.785834, longitude: -122.406417)
        let camera = CameraOptions(center: center, zoom: 15)
        mapView = MapView(frame: view.bounds, mapInitOptions: MapInitOptions(cameraOptions: camera))
        
        mapView.mapboxMap.onNext(.mapLoaded) { event in
            self.mapView.location.options.puckType = .puck2D()
        }

        view.addSubview(mapView)
        
        mapView.translatesAutoresizingMaskIntoConstraints = false
        mapView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor, constant: 0).isActive = true
        mapView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor, constant: 0).isActive = true
        mapView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor, constant: 0).isActive = true
        mapView.bottomAnchor.constraint(equalTo: self.view.bottomAnchor, constant: 0).isActive = true
        
        let barButton = UIBarButtonItem(barButtonSystemItem: .refresh, target: self, action: #selector(loadAnnotations))
        self.navigationItem.rightBarButtonItems = [barButton]
    }
    
    @objc func loadAnnotations() {
        let coordinates = [CLLocationCoordinate2D(latitude: 45.59989547729492, longitude: -122.65376281738281),
                           CLLocationCoordinate2D(latitude: 45.61619567871094, longitude: -122.6861801147461),
                           CLLocationCoordinate2D(latitude: 45.401817321777344, longitude: -122.76468658447266),
                           CLLocationCoordinate2D(latitude: 45.67732238769531, longitude: -122.65861511230469),
                           CLLocationCoordinate2D(latitude: 45.39260482788086, longitude: -122.80067443847656),
                           CLLocationCoordinate2D(latitude: 45.66080856323242, longitude: -122.56644439697266),
                           CLLocationCoordinate2D(latitude: 45.37034225463867, longitude: -122.60320281982422),
                           CLLocationCoordinate2D(latitude: 45.370635986328125, longitude: -122.6017837524414),
                           CLLocationCoordinate2D(latitude: 45.54340744018555, longitude: -122.44422149658203),
                           CLLocationCoordinate2D(latitude: 45.496944427490234, longitude: -122.91444396972656),
                           CLLocationCoordinate2D(latitude: 45.54230880737305, longitude: -122.41593170166016),
                           CLLocationCoordinate2D(latitude: 45.49683380126953, longitude: -122.94526672363281),
                           CLLocationCoordinate2D(latitude: 45.33603286743164, longitude: -122.76194763183594),
                           CLLocationCoordinate2D(latitude: 45.71255874633789, longitude: -122.77332305908203),
                           CLLocationCoordinate2D(latitude: 45.538307189941406, longitude: -122.37909698486328),
                           CLLocationCoordinate2D(latitude: 45.75018310546875, longitude: -122.67137145996094),
                           CLLocationCoordinate2D(latitude: 45.74995422363281, longitude: -122.7716293334961),
                           CLLocationCoordinate2D(latitude: 45.382476806640625, longitude: -122.40570068359375),
                           CLLocationCoordinate2D(latitude: 45.77881622314453, longitude: -122.67074584960938),
                           CLLocationCoordinate2D(latitude: 45.27581787109375, longitude: -122.77339172363281),
                           CLLocationCoordinate2D(latitude: 45.269744873046875, longitude: -122.7773208618164),
                           CLLocationCoordinate2D(latitude: 45.25453186035156, longitude: -122.70895385742188),
                           CLLocationCoordinate2D(latitude: 45.49700164794922, longitude: -122.29000091552734),
                           CLLocationCoordinate2D(latitude: 45.79849624633789, longitude: -122.67949676513672),
                           CLLocationCoordinate2D(latitude: 45.531639099121094, longitude: -122.28334045410156),
                           CLLocationCoordinate2D(latitude: 45.77690887451172, longitude: -122.86572265625),
                           CLLocationCoordinate2D(latitude: 45.80828857421875, longitude: -122.61548614501953),
                           CLLocationCoordinate2D(latitude: 45.233089447021484, longitude: -122.80652618408203),
                           CLLocationCoordinate2D(latitude: 45.23371505737305, longitude: -122.80978393554688),
                           CLLocationCoordinate2D(latitude: 45.28573226928711, longitude: -122.95242309570312),
                           CLLocationCoordinate2D(latitude: 45.80263137817383, longitude: -122.4902114868164),
                           CLLocationCoordinate2D(latitude: 45.248069763183594, longitude: -122.89376831054688),
                           CLLocationCoordinate2D(latitude: 45.29645919799805, longitude: -122.35675811767578),
                           CLLocationCoordinate2D(latitude: 45.82939529418945, longitude: -122.83942413330078),
                           CLLocationCoordinate2D(latitude: 45.84971618652344, longitude: -122.70497131347656),
                           CLLocationCoordinate2D(latitude: 45.764068603515625, longitude: -122.33875274658203),
                           CLLocationCoordinate2D(latitude: 45.86417770385742, longitude: -122.70453643798828),
                           CLLocationCoordinate2D(latitude: 45.76385498046875, longitude: -122.32445526123047),
                           CLLocationCoordinate2D(latitude: 45.85260009765625, longitude: -122.82817077636719),
                           CLLocationCoordinate2D(latitude: 45.85014343261719, longitude: -122.87225341796875),
                           CLLocationCoordinate2D(latitude: 45.229000091552734, longitude: -122.36399841308594),
                           CLLocationCoordinate2D(latitude: 45.90654754638672, longitude: -122.73927307128906),
                           CLLocationCoordinate2D(latitude: 45.67300033569336, longitude: -122.15599822998047),
                           CLLocationCoordinate2D(latitude: 45.13859939575195, longitude: -122.53580474853516),
                           CLLocationCoordinate2D(latitude: 45.13856506347656, longitude: -122.53498077392578),
                           CLLocationCoordinate2D(latitude: 45.15327072143555, longitude: -122.88248443603516),
                           CLLocationCoordinate2D(latitude: 45.91254806518555, longitude: -122.80207061767578),
                           CLLocationCoordinate2D(latitude: 45.938804626464844, longitude: -122.67121887207031),
                           CLLocationCoordinate2D(latitude: 45.818782806396484, longitude: -122.25225830078125),
                           CLLocationCoordinate2D(latitude: 45.73732376098633, longitude: -123.1925048828125)]
        self.addAnnotations(coordinates: coordinates)
        self.showAnnotationsInVisibleRect(annotations, animated: true)
    }

    func addAnnotations(coordinates: [CLLocationCoordinate2D]) {
        let first = coordinates.first
        
        let annotations = coordinates.map { coordinate -> PointAnnotation in
            var annotation = PointAnnotation(id: UUID().uuidString, coordinate: coordinate)
            if coordinate == first {
                annotation.image = PointAnnotation.Image(image: UIImage(named: "Public_Selected")!, name: "custom-marker-selected")
            } else {
                annotation.image = PointAnnotation.Image(image: UIImage(named: "Public")!, name: "custom-marker")
            }
            return annotation
        }

        // Initialize the map's point annotation manager.
        pointAnnotationManager = mapView.annotations.makePointAnnotationManager()

        // Pass the point annotations into the annotation manager.
        // This will add them to the map.
        pointAnnotationManager.annotations = annotations
        pointAnnotationManager.syncSourceAndLayerIfNeeded()
    }
    
    func showAnnotationsInVisibleRect(_ annotations: [PointAnnotation], animated: Bool) {
        let coordinates = annotations.map({$0.point.coordinates})
        showCoordinatesInVisibleRect(coordinates: coordinates, animated: animated)
    }
    
    func showCoordinatesInVisibleRect(coordinates: [CLLocationCoordinate2D], animated: Bool) {
        let padding = UIEdgeInsets.zero
        let camera = mapView.mapboxMap.camera(for: coordinates,
                                              padding: padding,
                                              bearing: nil,
                                              pitch: nil)
        
        if animated {
            mapView.camera.fly(to: camera, duration: 1.0, completion: nil)
        } else {
            mapView.mapboxMap.setCamera(to: camera)
        }
    }
}
`

**Comment by endanke** [comment] 2021-11-05 08:08
This appears to be fixed in the upcoming GL-Native release. I'll retest it when it's available!

**Comment by endanke** [comment] 2021-11-05 09:35
We've verified that the issue is related to the screen coordinate conversion, when the y coordinate gets clamped to horizon. Interestingly it clamps it even if the pitch is zero and the horizon shouldn't be visible. I'll check the implementation of that function and fix it in the upcoming release.

**Closed** 2022-01-21 19:00 UTC
Labels: bug :beetle:

**Comment by endanke** [comment] 2022-01-27 12:26
@lmelnykmylivn could you give it another try using our latest release? https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.3.0-rc.1

**Comment by lmelnykmylivn** [comment] 2022-03-25 09:51
Hi @endanke, sorry for late response, couldn't check before v10.3.0 wend to release. The issue looks like fixed. Thanks!
