### ISSUE TITLE
SymbolLayer, expression not working for textField and size

### ISSUE THREAD

**Issue by abouroubi** [mapbox/mapbox-maps-ios#2048] opened 2023-11-06 11:33 UTC
## Environment

- Xcode version: 15
- iOS version: 17
- Devices affected: all
- Maps SDK Version: 10.16.1

## Observed behavior and steps to reproduce

I want to implement a simple feature: Showing icons on the map, and when the user tap on an icon, I change the size and color of the icon, and update the text.

The code below can be run standalone in any project with Mapbox.

The issue is that with the same expression, the text color changes, but the icon size is not, neither the text. I'm I missing something ? Or is it a bug ?

```swift
import MapboxMaps
import UIKit

class ViewController: UIViewController {
    var mapView: MapView!
    
    let iconsSourceId = "icons-source"
    let iconsLayerId = "icons-layer"
    private var iconsLayer: SymbolLayer!
    private var iconsSource = GeoJSONSource()
    private var previouslyTappedIconId: String = ""
    private let iconsList = [
        "sun.min",
        "sun.min.fill"
    ]
    
    override public func viewDidLoad() {
        super.viewDidLoad()
        
        let myResourceOptions = ResourceOptions(accessToken: "YOUR_KEY")
        let myMapInitOptions = MapInitOptions(resourceOptions: myResourceOptions)
        mapView = MapView(frame: view.bounds, mapInitOptions: myMapInitOptions)
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        
        iconsLayer = SymbolLayer(id: iconsLayerId)
        
        mapView.mapboxMap.onNext(event: .mapLoaded) { [weak self] _ in
            guard let self = self else { return }
            
            self.setupIcons(style : self.mapView.mapboxMap.style)
            
            // Set up tap gesture
            let tapGesture = UITapGestureRecognizer(target: self, action: #selector(self.findFeatures))
            self.mapView.addGestureRecognizer(tapGesture)
        }
        
        view.addSubview(mapView)
    }
    
    /**
     Use the tap point received from the gesture recognizer to query
     the map for rendered features at the given point within the layer specified.
     */
    @objc public func findFeatures(_ sender: UITapGestureRecognizer) {
        let tapPoint = sender.location(in: mapView)
        
        mapView.mapboxMap.queryRenderedFeatures(with: tapPoint) { [weak self] result in
                
            guard let self = self else { return }
                
            switch result {
            case .success(let queriedfeatures):
                // Extract the feature from the queried features
                if let firstFeature = queriedfeatures.first, firstFeature.source == iconsSourceId {
                    let feature = firstFeature.feature;
                    guard case .number(let selectedIdDouble) = feature.identifier,
                          case .point(let point) = feature.geometry
                    else {
                        return
                    }
                    
                    let selectedId = Int(selectedIdDouble).description
                    
                    // Set the icon to be "selected"
                    setSelectedState(mapView, iconId: selectedId)
                    
                    // Reset a previously tapped icon to be "unselected".
                    resetPreviouslySelectedStateIfNeeded(mapView, currentTappedIconId: selectedId)
                    
                    // Store the currently tapped icon so it can be reset when another icon is tapped.
                    previouslyTappedIconId = selectedId
                    
                    // Center the selected icon on the screen
//                    mapView.camera.fly(to: CameraOptions(center: point.coordinates, padding: .init(top: 15, left: 15, bottom: 15, right: 15), zoom: 18))
                } else {
                    // No icons slected, we deselect the old one
                    // Reset a previously tapped icon to be "unselected".
                    resetPreviouslySelectedStateIfNeeded(mapView, currentTappedIconId: "")
                    
                    // Store the currently tapped icon so it can be reset when another icon is tapped.
                    previouslyTappedIconId = ""
                }
            case .failure(let error):
                print("An error occurred: \(error.localizedDescription)")
            }
        }
    }
    
    private func setupIcons(style: Style) {
        do {
            iconsSource.generateId = true
            iconsLayer.source = iconsSourceId
            
            for icon in iconsList {
                if let image = UIImage(systemName: icon) {
                    try? style.addImage(image, id: icon)
                }
            }
            
            iconsLayer.iconAnchor = .constant(.top)
            iconsLayer.textAnchor = .constant(.bottom)
            
            let isSelected = Exp(.boolean) {
                Exp(.featureState) { "selected" }
                false
            }
            
            iconsLayer.iconImage = .expression(Exp(.switchCase) {
                isSelected
                "sun.min.fill"
                
                "sun.min"
            })
                        
            iconsLayer.iconSize = .expression(Exp(.switchCase) {
                isSelected
                4.0
                
                2.0
            })
            iconsLayer.textField = .expression(Exp(.switchCase) {
                isSelected
                "Selected"
                
                "Not selected"
            })
            
            iconsLayer.textColor = .expression(Exp(.switchCase) {
                isSelected
                "#fff7ec"
                
                "#f00"
            })
            
            iconsLayer.iconColor = .expression(Exp(.switchCase) {
                isSelected
                "#fff7ec"
                
                "#f00"
            })
            
            let features = mapMyPointsToFeatures(loadData())
            
            iconsSource.data = .featureCollection(FeatureCollection(features: features))
            
            try style.addSource(iconsSource, id: iconsSourceId)
            try style.addLayer(iconsLayer)
        } catch {
            print("Error setting up disabled curb zones icons layer: \(error)")
        }
    }
    
    func updateData(style: Style, data: [MyPoint]) {
        let iconFeatures = mapMyPointsToFeatures(data)
        
        do {
            try style.updateGeoJSONSource(withId: iconsSourceId, geoJSON: .featureCollection(FeatureCollection(features: iconFeatures)))
        } catch {
            print(error.localizedDescription)
        }
    }
    
    private func setSelectedState(_ mapView: MapView, iconId: String) {
        mapView.mapboxMap.setFeatureState(sourceId: iconsSourceId,
                                          sourceLayerId: nil,
                                          featureId: iconId,
                                          state: ["selected": true])
        mapView.mapboxMap.getFeatureState(sourceId: iconsSourceId, featureId: iconId) { stateResult in
            switch stateResult {
            case .success(let state):
                // Access the feature state values
                let value = state["selected"]
                
                // Use the feature state value as needed
                print("The value of your feature state is: \(value ?? "")")
            case .failure(let error):
                // Handle the failure case
                print("Failed to get feature state: \(error)")
            }
        }
    }
    
    // Resets the previously selected earthquake to be "unselected" if needed.
    private func resetPreviouslySelectedStateIfNeeded(_ mapView: MapView, currentTappedIconId: String) {
        if previouslyTappedIconId != "", currentTappedIconId != previouslyTappedIconId {
            // Reset a previously tapped earthquake to be "unselected".
            mapView.mapboxMap.setFeatureState(sourceId: iconsSourceId,
                                              sourceLayerId: nil,
                                              featureId: previouslyTappedIconId,
                                              state: ["selected": false])
            
            mapView.mapboxMap.getFeatureState(sourceId: iconsSourceId, featureId: previouslyTappedIconId) { stateResult in
                switch stateResult {
                case .success(let state):
                    // Access the feature state values
                    let value = state["selected"]
                    
                    // Use the feature state value as needed
                    print("The value of your feature state is: \(value ?? "")")
                case .failure(let error):
                    // Handle the failure case
                    print("Failed to get feature state: \(error)")
                }
            }
        }
    }
    
    func updateVisibility(visible: Bool, style: Style) {
        let visibility: Value<Visibility> = visible ? .constant(.visible) : .constant(.none)
        
        try? style.updateLayer(withId: iconsLayerId, type: SymbolLayer.self) { (layer: inout SymbolLayer) in
            layer.visibility = visibility
        }
    }
    
    private func mapMyPointsToFeatures(_ points: [MyPoint]) -> [Feature] {
        var iconsFeatures = [Feature]()
        
        for point in points {
            let iconCoordinate = CLLocationCoordinate2D(latitude: point.geoPoint2d[1], longitude: point.geoPoint2d[0])
            let pointGeometry = Point(iconCoordinate)
            var iconFeature = Feature(geometry: pointGeometry)
            // iconFeature.identifier = .string(point.id)
            iconFeature.properties = [
                "id": .string(point.id),
            ]
            iconsFeatures.append(iconFeature)
        }
        
        return iconsFeatures
    }
    
    private func loadData() -> [MyPoint] {
        let decoder = JSONDecoder()
        let json = """
        [
                {
                    "id": "custom_string_id",
                    "geoPoint2d": [
                       10,
                       0
                    ]
                },
                {
                    "id": "custom_string_id_2",
                    "geoPoint2d": [
                        -10,
                        0
                    ]
                }
        ]
        """
        do {
            // Decode the JSON into an array of intermediate structs
            let points = try decoder.decode([MyPoint].self, from: Data(json.utf8))
            
            // Convert DTOs to your domain model
            let result = points.map { dto -> MyPoint in
                MyPoint(
                    id: dto.id,
                    geoPoint2d: dto.geoPoint2d
                )
            }
            
            return result
        } catch {
            print(error)
            return []
        }
    }
}



struct MyPoint: Decodable {
    let id: String
    let geoPoint2d: [Double]
    
    init(id: String, geoPoint2d: [Double]) {
        self.id = id
        self.geoPoint2d = geoPoint2d
    }
}
```

## Expected behavior

Text, size and color of the tapped icon should update.

**Comment by maios** [comment] 2023-11-09 10:14
Ideally you shouldn't have to, we will update our doc to have better clarity of feature-state usage. I am closing this issue now as this is not a bug, if you need help still with the above solutions, please open a new issue or ask on our  [Mapbox Developer Discord](https://docs.mapbox.com/help/getting-started/mapbox-developer-discord/). Thank you :)

**Closed by maios** 2023-11-09 10:14 UTC
Labels: bug :beetle:

**Comment by abouroubi** [comment] 2023-11-09 13:21
Ok, I understand better now.
Concerning asking questions on the Discord, I already did, but I did not have any answer, that's why I thought it was a bug and opened an issue here.

**Comment by skg54** [comment] 2025-01-08 12:14
> Hi @abouroubi , `feature-state` only supports paint properties that support data-driven styling, in your example, SymbolLayer/textField and SymbolLayer/iconSize are not a paint property, if you want to change the icon image upon selected/deselected
> 
> Source: https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#feature-state
> 
> To achieve what you stated, I highly recommend you to use [PointAnnotationManager](https://docs.mapbox.com/ios/maps/api/10.16.1/Classes/PointAnnotationManager.html), however, you can also do so by making the properties data-driven
> 
> ```
> // Tells renderer to use the data-driven property value
> iconsLayer.iconSize = .expression(
>   Exp(.get) { "data-driven-icon-size" }
> )
> 
> // when selected state is toggled
> private func setSelected(id: Double) {
>   // Get all features of the layer and source
>   mapView.mapboxMap.querySourceFeatures(
>       for: iconsSourceId,
>       options: SourceQueryOptions(sourceLayerIds: [iconsLayerId], filter: NSNull())
>   ) { [weak self] result in
>       guard let self else { return }
> 
>       switch result {
>       case .success(let sourceFeatures):
>           let geojson = FeatureCollection(features: sourceFeatures.map {
>               // Update feature's properties
>               var feature = $0.feature
>               if feature.identifier == .string(String(id)) || feature.identifier == .number(id) {
>                   feature.properties?["data-driven-icon-size"] = 2
>               } else {
>                   feature.properties?["data-driven-icon-size"] = 1
>               }
>               return feature
>           })
>           try? self.mapView.mapboxMap.style.updateGeoJSONSource(withId: iconsSourceId, geoJSON: .featureCollection(geojson))
> 
>       case .failure(let failure):
>           print("An error occurred: \(failure.localizedDescription)")
>       }
>   }
> }
> ```

For folks with lighter weight point data but need the flexibility of SymbolLayer - like data-driven properties, label and icon collision/overlap issues, etc  

Use a 1-to-1 GeoJSONSource for each SymbolLayer.  It's a much cleaner than several layers within a single GeoJSONSource.


![IMG_4150](https://github.com/user-attachments/assets/37e1fd5e-d450-43f3-99a4-19e5ada04e1c)
