### ISSUE TITLE
Crash: Failed to create SourceType from "customvector"

### ISSUE THREAD

**Issue by PrisakarMaksim** [mapbox/mapbox-maps-ios#1079] opened 2022-02-01 12:26 UTC
## Environment

- Xcode version: 13.2.1
- iOS version: 15.2
- Devices affected: Simulator
- Maps SDK Version: 10.1.0

## Observed behavior and steps to reproduce

1. Add GeoJsonSource to style
2. Add custom tiles source  via `addCustomGeometrySource` to style
3. Call `updateGeoJSONSource` for the first source

Result: app crashed with `Failed to create SourceType from customvector`

## Notes / preliminary analysis

Probably `addCustomGeometrySource` creates  source with type "customvector" under the hood, witch not containes in SourceType enum

## Additional links and references

<img width="1017" alt="Screenshot 2022-02-01 at 15 07 41" src="https://user-images.githubusercontent.com/90187891/151967202-d548f32f-53f9-44b3-8fd4-46c235a74d66.png">
<img width="1019" alt="Screenshot 2022-02-01 at 15 07 29" src="https://user-images.githubusercontent.com/90187891/151967207-30922566-e70d-498d-8b5f-c8cb9777c0b8.png">

**Comment by ZiZasaurus** [comment] 2022-02-01 14:12
Closing as a duplicate of https://github.com/mapbox/mapbox-maps-ios/issues/871

**Closed by ZiZasaurus** 2022-02-01 14:12 UTC
Labels: bug :beetle:
