### ISSUE TITLE
LocalizationExample crashes on "Choose Language"

### ISSUE THREAD

**Issue by richardpineo** [mapbox/mapbox-maps-ios#904] opened 2021-12-07 02:18 UTC
## Environment

- Xcode version: 13.1
- iOS version: 15.1
- Devices affected: all?
- Maps SDK Version: 10

## Observed behavior and steps to reproduce

Run the example LocalizationExample and tap the choose language button. The application crashes with an unhandled exception.

## Expected behavior

It should not crash

## Notes / preliminary analysis

You need to provide a source view or other location for the alert action sheet.
adding the line fixes it:
alert.popoverPresentationController?.sourceView = sender
![image](https://user-images.githubusercontent.com/8593979/144954045-be1a0d9a-5ef2-4ded-a75f-1414b4e38108.png)

**Comment by ZiZasaurus** [comment] 2021-12-08 16:00
@richardpineo, I am unable to reproduce this behavior on v10 or our latest version v10.1.0. Can you please let me know if you are still seeing this on v10.1.0?

**Comment by ZiZasaurus** [comment] 2021-12-15 18:49
Closing this ticket but please feel free to reopen if you have any additional questions.

**Closed by ZiZasaurus** 2021-12-15 18:49 UTC
Labels: bug :beetle:
