### ISSUE TITLE
PointAnnotation declares `userInfo` as [String:Any] but strips non json objects

### ISSUE THREAD

**Issue by mfazekas** [mapbox/mapbox-maps-ios#2059] opened 2023-11-21 19:55 UTC
## Environment

- Xcode version: 10.4.3
- iOS version: 16.4
- Devices affected: iOS Simulator
- Maps SDK Version:11.0.0-rc.2

## Observed behavior and steps to reproduce

userInfo in PointAnnotation and other annotation declared as `[String:Any]` but it's converted to json so non json objects are removed. 

```swift
    func testFoo() {
      var customPointAnnotation = PointAnnotation(coordinate: CLLocationCoordinate2D(latitude: 40.7142, longitude: -74.00597))
      customPointAnnotation.image = .init(image: UIImage(named: "dest-pin")!, name: "rnmbx-custom-image-name")
      customPointAnnotation.userInfo = ["foo": (42, "42")]
      print("foo: \(customPointAnnotation.userInfo)")
    }
```

Output:
```
foo: Optional(["foo": nil])
```

## Expected behavior

```
foo: Optional(["foo": (42, "42")])
```

## Notes / preliminary analysis

10.* we could store anything in userInfo as declared. 11.* only allows json objects.

Our use case is storing the point annotation reference so we can use it on tap handler. 

```swift
annotation.userInfo = [RNMBXPointAnnotation.key:WeakRef(self)]

...

 func onTap(annotations: [Annotation]) {
    guard annotations.count > 0 else {
      fatalError("didDetectTappedAnnotations: No annotations found")
    }
    
    for annotation in annotations {
      if let pointAnnotation = annotation as? PointAnnotation,
         let userInfo = pointAnnotation.userInfo {
        
        if let poinAnnotationRef = userInfo[RNMBXPointAnnotation.key] as? WeakRef<RNMBXPointAnnotation> {
          if let pointAnnotation= poinAnnotationRef.object {
            pointAnnotation.handleTap(..)
          }
...
```

https://github.com/rnmapbox/maps/blob/f83d89e37a79a91f24136eab77b77dea975a3538/ios/RNMBX/RNMBXPointAnnotation.swift#L19C1-L19C63

https://github.com/rnmapbox/maps/blob/f83d89e37a79a91f24136eab77b77dea975a3538/ios/RNMBX/RNMBXMapView.swift#L1360-L1364

## Additional links and references

Was changed in this commit: 

https://github.com/mapbox/mapbox-maps-ios/commit/1c102f6cb35a121c452d2c1f79702d40f7b23c5b#diff-bd177973d4ce8b4a35d6e6e1fb2ed646ba9abb05782ecfc99da27fca75f71e27R25-R33

As I understand the change makes it easier to convert to feature properties, but I think either interface should show JSON only objects. Or should convert only to json when needed.

**Comment by pjleonard37** [comment] 2023-11-22 16:15
Hi @mfazekas -- 

Thanks for reporting and sharing this level of detail. I can reproduce this on our side. I'm going to take this back to the broader team for discussion.

**Comment by matulik** [comment] 2023-12-06 13:10
same issue for me - in v10 I store associated model object in userobject, for now I can't do that because it try to convert it to JSON

**Comment by akirmse** [comment] 2024-01-08 14:39
I have the same problem, which is preventing me from moving to v11 for iOS (Android is fine, doesn't have this problem).  Is this going to be reverted in the next version, or is this a permanent API change?

IMO, if the Mapbox library internally wants to treat the userInfo field as JSON in some cases, it should do so by casting the userInfo field itself, not by changing the internals of the field.

**Comment by aleksproger** [comment] 2024-01-08 14:44
👋 @akirmse, thanks for adding on this. We aware of the issue and fix is currently already in progress.

**Closed** 2024-01-11 06:28 UTC
Labels: bug :beetle:, v11

**Comment by akirmse** [comment] 2024-01-11 17:10
@aleksproger  I see this change: https://github.com/mapbox/mapbox-maps-ios/commit/4f7f2476b7a463bbe9678f60ead4d733d273db89

Hoping you might explain the recommended way to store arbitrary non-JSON data in the future.  What I see is:

- userInfo is reverted to the v10 behavior, but it is deprecated.
- There is a new field customData that is not deprecated, but it strips non-JSON data.

Is there a non-deprecated way to store arbitrary user data with annotations?  Is userInfo going to be removed?
