### ISSUE TITLE
PointAnnotation.image ignores dynamically generated UIImages

### ISSUE THREAD

**Issue by AndreasVerhoeven** [mapbox/mapbox-maps-ios#806] opened 2021-11-03 10:52 UTC
I'm trying to figure out how to add a marker to the map with a title below it. This turns out to be an exercise in frustration: the v10 SDK seems to lack major features from the previous SDK unfortunately and requires us to rewrite large parts of our code for no gain at all (in fact, the user and developer experience is getting worse).

Right now, our plan is to use a PointAnnotation with a pre-rendered image that resembles a marker + label. However, this doesn't seem to work. Dynamically generated images do not seem to work. What are our options here apart from dropping mapbox and finding another vendor?

## Environment

- Xcode version: 13.1
- iOS version: 15.0
- Devices affected:
- Maps SDK Version: 10.0.1

## Observed behavior and steps to reproduce
```
var annotation = PointAnnotation(id: UUID().uuidString, coordinate: someCoordinate)
var.image = UIGraphicsImageRenderer(size: size).image { context in
 // render image here
}
// add annotation to map
```
- Annotation never shows up

## Expected behavior
- Annotation shows up

**Comment by AndreasVerhoeven** [comment] 2021-11-03 11:19
It seems that images must be smaller than 42 points in width, otherwise they don't show up. How do we add labels to markers?

**Comment by ZiZasaurus** [comment] 2021-11-03 16:04
@AndreasVerhoeven, I'm unable to reproduce this behavior by replacing [these lines](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/MultiplePointAnnotationsExample.swift#L30-L32) with your dynamically generated image on the latest version of our SDK. Could you please provide a minimal test case?

**Comment by macdrevx** [comment] 2021-11-03 16:23
I think the root cause of this issue is the same as in #416 and #600 which were fixed in v10.1.0-rc.1. @AndreasVerhoeven when you verify with the latest version, be sure to try that version or later.

**Comment by AndreasVerhoeven** [comment] 2021-11-03 16:29
@macdrevx there doesn't seem to be a newer release than `v10.0.1` available .The current release we got thru Cocoapods still has this issue. How do we get this version?

SDK v10 seems far from production ready for us, but the old SDK is already deprecated and unsupported? We're pretty disappointed with mapbox at the moment.

**Comment by ZiZasaurus** [comment] 2021-11-04 14:10
@AndreasVerhoeven, apologies for any confusion and thank you for your feedback. Using the following snippet, you can add the [newest release](https://github.com/mapbox/mapbox-maps-ios/releases) to your project: 

```
pod 'MapboxMaps', '10.1.0-rc.1'
```

While v6 is not yet deprecated, only critical bug fixes and feature requests will be implemented at this time. Aside from this behavior, are there any other issues that you're experiencing that are hampering your development?

**Comment by ZiZasaurus** [comment] 2021-11-16 14:33
Closing this ticket for now, however, If this does not answer your question please feel free to reopen.

**Closed by ZiZasaurus** 2021-11-16 14:33 UTC
Labels: bug :beetle:
