### ISSUE TITLE
Zoom and pan during Pitch gesture

### ISSUE THREAD

**Issue by mfazekas** [mapbox/mapbox-maps-ios#1958] opened 2023-05-13 20:00 UTC
## Environment

- Xcode version:14.2
- iOS version:16.2
- Devices affected:Simulator iPhone 14 Pro Max
- Maps SDK Version: 10.3.1

## Observed behavior and steps to reproduce

The new Mapbox version (10.13.1) allows to combine multiple gestures. 
This means you can zoom/pan during a pitch gesture, which can be confusing.
https://github.com/mapbox/mapbox-maps-ios/assets/52435/45af95b3-8ba1-4f3a-b33a-6aacc6539943

*Note* the video was recorded in simulator, but on device this behaviour is more confusing

## Expected behavior

As with 10.12.* a gesture started as pitch should be pitch and not allow other gestures. 

https://github.com/mapbox/mapbox-maps-ios/assets/52435/f70c85c1-ab9c-4c00-81e2-9ca484555415

## Notes / preliminary analysis

The issue seems to be caused by 48b6be7f57f8c52c2ece5d8cbde4eda9ec41b007

**Comment by baleboy** [comment] 2023-05-16 05:55
Thanks for report the issue and for tracking down the change that caused it. We'll take it into our backlog for fixing.

**Comment by persidskiy** [comment] 2023-06-01 13:02
@mfazekas The issue is fixed in the new `v10.14.0-rc.1` [release](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v10.14.0-rc.1) , please try it out.

I'm closing this issue, feel free to reopen it if the fix doesn't work.

**Closed by persidskiy** 2023-06-01 13:02 UTC
Labels: bug :beetle:
